### ISSUE TITLE
Unable to access https://tekton.dev

### ISSUE THREAD

**Issue by hrishin** [tektoncd/website#1]
Getting the following error if I'm trying to access it

![image](https://user-images.githubusercontent.com/28615674/54187694-279f0800-44d4-11e9-8b07-d783a62986ae.png)

**Comment by lucperkins** [comment]
This appears to have been fixed: https://tekton.dev/

**Comment by caniszczyk** [comment]
danke!

**Comment by hrishin** [comment]
Thank you for resolving and closing it :)

**Comment by bobcatfish** [comment]
woot, the first issue in the repo 🎉 

@dlorenc was wrestling with this over the last couple days - glad it's working now and thanks for reporting and dealing with it all ❤️
