### ISSUE TITLE
Create versioned docs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/website#10]
# Expected Behavior

We should have hosted and versioned Tekton docs, based on the markdown files we have in each repo, maybe starting with just Pipelines.

# Actual Behavior

* Pipelines docs are always tracking head: https://github.com/tektoncd/pipeline/tree/master/docs
* Or you can go to a lot of trouble and view them at the tag https://github.com/tektoncd/pipeline/tree/v0.4.0/docs which probably no one ever does cuz it's a hassle

**Comment by dibyom** [comment]
The Readme now has a table of versioned docs. So I think it should be safe to close this out?
