### ISSUE TITLE
Move dashboard tutorial to Tektoncd/website repo + add license file

### ISSUE THREAD

**Issue by anneqm** [tektoncd/website#101]
# Expected Behavior
The preferred location for tekton tutorials, in particular those displayed/referenced on https://tekton.dev/try/ should be located within the tekton github repo
Desired changes to consider:

1. Move tutorial from  https://github.com/ncskier/katacoda/  to a tutorial folder on the https://github.com/tektoncd/website
2. Use a Tekton Id with the katacoda
3. Add appropriate license file
    - reference https://github.com/ncskier/katacoda/issues/2#issue-608759758
4. consider where to store translation copy
     
# Actual Behavior
tutorial opens in personal repo

# Steps to Reproduce the Problem

# Additional Info

**Comment by AlanGreene** [comment]
@afrittoli @popcor255 following up on the Katacoda discussion from yesterday's docs working group (sorry I couldn't make it, just watched the recording now).

The request in 2. here is to use a Tekton functional id (Christie mentioned on the pipelines WG a few weeks ago that there are several that may be used) to create a [Katacoda author profile](https://www.katacoda.community/author-profile.html) so we could have something like https://katacoda.com/tektoncd, then link this account to the website repo by setting up the webhook following the author profile docs.

**Comment by jjasghar** [comment]
https://github.com/tektoncd/website/pull/143 this should be what's needed to get the first done.

**Comment by AlanGreene** [comment]
We're live! 🎉 Thanks @jjasghar and @afrittoli 

https://katacoda.com/tektoncd

/close
