### ISSUE TITLE
Link to Tekton presentations?

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/website#115]
# Expected Behavior

That I can find the good Tekton presentations, that I know exists (e.g. from KubeCon), from the website.

# Actual Behavior

There are mostly static content on the website. It would be great to link to good Tekton presentations, unless there are valid reasons this is not done.

**Comment by AlanGreene** [comment]
Also related: https://github.com/tektoncd/website/issues/102

**Comment by vdemeester** [comment]
yeah, we could list some of the kubecon & co talks that are available on youtube on the website :+1:
