### ISSUE TITLE
Publish API references

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/website#117]
As part of tekton.dev documentation, we should publish the API references of our APIs

See https://knative.dev/docs/reference/ and https://knative.dev/docs/reference/serving-api/ as an example

/kind documentation

**Comment by afrittoli** [comment]
The knative API docs are generated using this: https://github.com/ahmetb/gen-crd-api-reference-docs
For pipeline we have now a swagger.json instead. Which one do we want to go for?

**Comment by afrittoli** [comment]
Reference is published at https://tekton.dev/docs/pipelines/pipeline-api/
@vdemeester ok to close?
