### ISSUE TITLE
Separate Syncing the docs from building and deploying the website framework.

### ISSUE THREAD

**Issue by popcor255** [tektoncd/website#122]
# Expected Behavior
In-order to have doc changes on the website you only have to run the sync script.

# Actual Behavior
You must sync the docs you have to sync, netlify build, and netlify deploy

# Additional Info

**Comment by AlanGreene** [comment]
Netlify deploys are atomic so it's not possible to sync additional content separately: https://docs.netlify.com/site-deploys/overview/

**Comment by popcor255** [comment]
Yeah, I saw that. However, the make file sync the doc then deploys to netlify. We could just run the sync script. However, I don't know what would be the use case because it wouldn't have any effect on the website.

**Comment by popcor255** [comment]
thanks @wlynch! :smile_cat:
https://github.com/tektoncd/website/pull/135
