### ISSUE TITLE
PipelineResources page has broken link for "the v1alpha1 to v1beta1 migration guide"

### ISSUE THREAD

**Issue by firmsoil** [tektoncd/website#125]
# Expected Behavior
The [the v1alpha1 to v1beta1 migration guide](https://tekton.dev/docs/pipelines/resources/) hyperlink on https://tekton.dev/docs/pipelines/resources/ should return the migration guide content webpage successfully.
# Actual Behavior
[the v1alpha1 to v1beta1 migration guide](https://tekton.dev/docs/pipelines/resources/) hyperlink on https://tekton.dev/docs/pipelines/resources returns 

Not found
Oops! This page doesn't exist. Try going back to our home page.
# Steps to Reproduce the Problem
Visit https://tekton.dev/docs/pipelines/resources/ and select the  hyperlink [the v1alpha1 to v1beta1 migration guide](https://tekton.dev/docs/pipelines/resources/).

**Comment by AlanGreene** [comment]
Thanks for reporting, looks like the migration guide isn't being synced to the website.

/assign
