### ISSUE TITLE
Update Contributing Guide for website repo

### ISSUE THREAD

**Issue by popcor255** [tektoncd/website#129]
# Expected Behavior
In general content for a specific project would reside in the docs folder of that project’s repo, and content involving multiple projects or higher level overviews would live in the website repo. However, I do not believe this is documented in the contributors guide. [contributors guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md)

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/website/blob/master/content/en/doc-con-main.md#submitting-a-documentation-change

@sergetron mentioned on the call today that he would be adding links to the docs contribution guide in a few other places.
