### ISSUE TITLE
Update tekton.dev with proper Linux Foundation privacy, terms, and CDF logo

### ISSUE THREAD

**Issue by danlopez00** [tektoncd/website#13]
# Expected Behavior

1. Place the following language 
"Copyright © {YYYY} The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page. Linux is a registered trademark of Linus Torvalds. Privacy Policy and Terms of Use"

Privacy URL: https://www.linuxfoundation.org/privacy
Terms URL: https://www.linuxfoundation.org/terms/

2. Replace {YYYY} with current year
3. CDF Icon Logo - https://github.com/cdfoundation/artwork/tree/master/cdf/icon/color
Other logos available - https://github.com/cdfoundation/artwork/tree/master/cdf

# Additional Info

Example: https://www.spinnaker.io/ footer for reference

**Comment by danlopez00** [comment]
ref: #11

**Comment by vdemeester** [comment]
@danlopez00 there is also https://github.com/tektoncd/website/pull/12 in progress :angel: (but we can go ahead and merge #11  while waiting for #12 to be ready :wink: )

**Comment by danlopez00** [comment]
@vdemeester @bobcatfish what is the status of updating the site with CDF and LF content

**Comment by vdemeester** [comment]
https://tekton-dev.netlify.com/ is the "soon-to-be" tekton.dev 
We need to update the footer to look more spinnaker-like :angel:

**Comment by danlopez00** [comment]
This is a great start! Yeah the Spinnaker.io site is the ideal state.
