### ISSUE TITLE
Changes for Sync to Multiple Releases

### ISSUE THREAD

**Issue by popcor255** [tektoncd/website#130]
# Expected Behavior
![image](https://user-images.githubusercontent.com/1755197/83038581-212e7a80-a00b-11ea-8e39-31cdf71a9d4d.png)

# Actual Behavior
![image](https://user-images.githubusercontent.com/1755197/83038504-078d3300-a00b-11ea-919c-9826318d4730.png)

**Comment by AlanGreene** [comment]
WIP: I'll fill in more details in this comment with gaps in the current support for multiple versions

**Comment by AlanGreene** [comment]
PR open https://github.com/tektoncd/website/pull/190
Most of the issues in my last comment above have since been addressed. There are still some styling improvements we could make but it's a much better experience than it was when I wrote the comment.
