### ISSUE TITLE
Added Interactive "Getting Started" tutorial to Try page

### ISSUE THREAD

**Issue by anneqm** [tektoncd/website#132]
# Expected Behavior
Interactive tutorials all available from the Interactive Tutorial section of the https://tekton.dev/try/ webpage. The one listed on the https://tekton.dev/docs/getting-started/ page perhaps could be repeated on the Try page. 

# Actual Behavior
There's a "Note: See also the Getting started with Tekton interactive tutorial."

# Steps to Reproduce the Problem
1. go to https://tekton.dev/docs/getting-started/
2. See button for interactive getting started tutorial.   This one is NOT available from the "try" page and probably should be.  

Thanks!

# Additional Info

**Comment by popcor255** [comment]
Yeah, I think this can be done know. Since, @jjasghar added material. Creating the katacoda should fairly simple.

**Comment by jjasghar** [comment]
:D 

Speaking of, shouldn't we move https://github.com/ncskier/katacoda/tree/master/tekton-dashboard into the actual tekton name space on github? (then we could create a bunch of these tutorials there)

**Comment by anneqm** [comment]
> 
> 
> :D
> 
> Speaking of, shouldn't we move https://github.com/ncskier/katacoda/tree/master/tekton-dashboard into the actual tekton name space on github? (then we could create a bunch of these tutorials there)

Yes!  we are waiting to get a "functional type" ID set up (per discussion on our working group meeting yesterday) and then that's the plan!

**Comment by jjasghar** [comment]
My team has some experience with those IDs, if you need some help i can set up a call with @mpetason and me to help walk you through it :)

**Comment by mpetason** [comment]
I did this recently so it is still fresh, definitely reach out if you need help. The guide can be confusing.

**Comment by AlanGreene** [comment]
Setting up the katacoda profile and moving the existing tutorial is being tracked in https://github.com/tektoncd/website/issues/101, recently discussed at the docs WG and in progress.

**Comment by anneqm** [comment]
Now that  #101 is done, can we add the "getting started interactive tutorial to the try page?  
it's still a bit bare.  Thanks all for the work to move and set up katacoda!

**Comment by jjasghar** [comment]
@anneqm the PR with this is right here: https://github.com/tektoncd/website/pull/145 🤘
