### ISSUE TITLE
Broken "Customizing basic execution parameters" hyperlink on https://tekton.dev/docs/pipelines/podtemplates/

### ISSUE THREAD

**Issue by firmsoil** [tektoncd/website#133]
# Expected Behavior
[Customizing basic execution parameters](https://tekton.dev/docs/pipelines/install#customizing-basic-execution-parameters) hyperlink on https://tekton.dev/docs/pipelines/podtemplates/ should return valid webpage content.

# Actual Behavior
[Customizing basic execution parameters](https://tekton.dev/docs/pipelines/install#customizing-basic-execution-parameters) hyperlink on https://tekton.dev/docs/pipelines/podtemplates/ returns 

Not found
Oops! This page doesn't exist. Try going back to our home page.

# Steps to Reproduce the Problem
Navigate to https://tekton.dev/docs/pipelines/podtemplates/ and select [Customizing basic execution parameters](https://tekton.dev/docs/pipelines/install#customizing-basic-execution-parameters) hyperlink.

**Comment by popcor255** [comment]
fixed #181 

/close
