### ISSUE TITLE
Broken observability configuration hyperlink on https://tekton.dev/docs/pipelines/metrics/

### ISSUE THREAD

**Issue by firmsoil** [tektoncd/website#134]
# Expected Behavior
[observability configuration](https://tekton.dev/docs/pipelines/config/config-observability.yaml) hyperlink on https://tekton.dev/docs/pipelines/metrics/ should return valid webpage content.

# Actual Behavior
[observability configuration](https://tekton.dev/docs/pipelines/config/config-observability.yaml) hyperlink on https://tekton.dev/docs/pipelines/metrics/ returns 

Not found
Oops! This page doesn't exist. Try going back to our home page.

# Steps to Reproduce the Problem
Navigate to https://tekton.dev/docs/pipelines/config/config-observability.yaml and select [observability configuration](https://tekton.dev/docs/pipelines/config/config-observability.yaml) hyperlink.

**Comment by popcor255** [comment]
Hello @firmsoil!
This was an issue opened before from https://github.com/tektoncd/website/issues/89
I think might be worth opening again. I know what the issue is: The python sync is using replacing the link when it is not suppose to. I can fix it. Unless, someone else beats me to it. :smile_cat:

**Comment by popcor255** [comment]
fixed #181 

/close
