### ISSUE TITLE
the website - tekton.dev, the demo on this website,the demo path maybe wrong --- the location is: Interactive Tutorial - step 2 of 6

### ISSUE THREAD

**Issue by gitupxm163** [tektoncd/website#156]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1.please fix the path: tekton-example ---> tekton-examples
2.
3.

# Additional Info

**Comment by jjasghar** [comment]
i believe when https://github.com/tektoncd/website/pull/145 is merged it would point to the correct version of the tutorials.
