### ISSUE TITLE
tekton.dev -demo,some command may be wrong --- the location is: Interactive Tutorial - step 2 of 6

### ISSUE THREAD

**Issue by gitupxm163** [tektoncd/website#157]
# Expected Behavior

when i run : mkdir /mnt/data && kubectl apply -f https://k8s.io/examples/pods/storage/pv-volume.yaml ......
the command Should execute correctly

Actual Behavior

mkdir: cannot create directory ‘/mnt/data’: File exists
the result like this ,so the next command won`t be execute

# Steps to Reproduce the Problem

1.maybe we should use : mkdir -p /mnt/data && command.... to avoid the problem
2.
3.

# Additional Info

**Comment by jjasghar** [comment]
i believe when https://github.com/tektoncd/website/pull/145 is merged the tutorial link should go to the new correct one.
