### ISSUE TITLE
Broken links to interceptor types

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/website#159]
# Expected Behavior
The links in the list of interceptors in https://tekton.dev/docs/triggers/eventlisteners/#interceptors point to the corresponding sections.

# Actual Behavior
None of the works, so the browsers just renders the same content from https://tekton.dev/docs/triggers/eventlisteners/#interceptors.

**Comment by AlanGreene** [comment]
Looks like the fragments need to be converted to lowercase to match the ids output by the website sync

- Broken: https://tekton.dev/docs/triggers/eventlisteners/#GitLab-Interceptors
- Working: https://tekton.dev/docs/triggers/eventlisteners/#gitlab-interceptors

**Comment by afrittoli** [comment]
We can `lower()` fragments throughout.

**Comment by afrittoli** [comment]
Actually we cannot do that, fragment can be case sensitive, so we should not arbitrarily lower them.
The link in github is lowercase:
```
<h3><a id="user-content-github-interceptors" class="anchor" aria-hidden="true" href="#github-interceptors"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>GitHub Interceptors</h3>
```

so, even if GitHub will also accept a camel-case version of it, the docs should be fixed on triggers side to use the lowercase.
