### ISSUE TITLE
Getting started guides for project

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/website#16]
We need better "Getting started guide" for the tekton projects.

- They should be on the `docs/` folder of each of those project (like `docs/getting-started/…`)
- Repositories to tackle
  - [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline)
  - [`tektoncd/triggers`](https://github.com/tektoncd/triggers) — the [existing one](https://github.com/tektoncd/triggers/tree/master/docs/getting-started) needs enhancement
  - [`tektoncd/cli`](https://github.com/tektoncd/cli)
  - [`tektoncd/dashboard`](https://github.com/tektoncd/dashboard)

/kind docs

**Comment by popcor255** [comment]
I am interested in helping. Ill take a crack at it.

**Comment by sergetron** [comment]
The first guide in the "Getting Started" series, ["Overview of Tekton"](https://github.com/tektoncd/website/blob/master/content/en/docs/getting-started-overview.md), has been recently published!
