### ISSUE TITLE
Tekton Workspaces

### ISSUE THREAD

**Issue by lrokman** [tektoncd/website#160]
# Expected Behavior
working links
# Actual Behavior
broken links

# Steps to Reproduce the Problem

1.check website

# Additional Info

links are broken or non-existent:

See the following in-depth examples of configuring Workspaces:

Workspaces in a TaskRun
Workspaces in a PipelineRun
Workspaces from a volumeClaimTemplate in a PipelineRun

**Comment by popcor255** [comment]
fixed #181 

/close
