### ISSUE TITLE
link is broken in Workspaces

### ISSUE THREAD

**Issue by larrycai** [tektoncd/website#162]
# Expected Behavior

When I click `Workspace in a TaksRun` in "For a more in-depth example, see [Workspaces in a TaskRun]()" in https://tekton.dev/docs/pipelines/workspaces/, it shall give me the correct link

# Actual Behavior

It is linked to non-exist link https://tekton.dev/docs/pipelines/examples/v1beta1/taskruns/workspace.yaml 

# Steps to Reproduce the Problem

1.  Open browser to https://tekton.dev/docs/pipelines/workspaces/
2.  Scroll to middle to "For a more in-depth example, see [Workspaces in a TaskRun]()" 
3.  Click the link 

# Additional Info

**Comment by popcor255** [comment]
dup of https://github.com/tektoncd/website/issues/160
/close
