### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by jhonmike** [tektoncd/website#165]
I would like to know if I can initially contribute to the project by translating the documentation into Portuguese?

This will help in my studies and I can also contribute to the project in a subtle way

**Comment by afrittoli** [comment]
Hi @jhonmike - thank you for this issue and sorry about the really late reply.

It would be great to have documentation in other languages!
There would be some development work to be done to make the documentation in other languages accessible, but I think this is definitely something worth investing on.

Are you still interested in pursuing this? 

@sergetron @bobcatfish @vdemeester @popcor255 @AlanGreene

**Comment by jhonmike** [comment]
Certainly! how can i help?

Can I start by creating an issue organizing tasks necessary to start the DOC translation process? can you help me with this?
