### ISSUE TITLE
Getting started with tekton

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/website#17]
Based on/Linked with #16, we should have a general getting started on tekton that brings together the key components of Tekton in a digestable, easy getting started guide.

Most likely based on something similar to [`tutorial.md`](https://github.com/tektoncd/pipeline/blob/master/docs/tutorial.md) but using the cli and triggers most likely.

> As part of the “Getting started with Tekton” we need to identify the documentation entry point (where to start reading) and include a link to it from Triggers, Pipelines, experimental, etc.

/kind documentation

**Comment by popcor255** [comment]
I will do an install.md and Hello.md
Propsal: Install.md and Hello.md

**Comment by popcor255** [comment]
I would like to take the story, 'getting started'. @vdemeester

**Comment by bobcatfish** [comment]
How's this going @popcor255 ?

p.s. + @spomorski who is working on some docs also

**Comment by popcor255** [comment]
Hi, @bobcatfish. I made a pr a while, but closed it cause the site was down.  I just re-opened it. https://github.com/tektoncd/website/pull/25. The getting started was basically a shorter version of another getting started guide.

**Comment by popcor255** [comment]
@bobcatfish Sorry for my hiatus. So, I pulled the changes from a few days ago. It looks like there is a file missing that was not included in the https://github.com/tektoncd/website/pull/24/files#r385423682. I want to make a pr, but I got it working removing code seemed pretty important for production. But, I also don't want to push a non-working version of the repo. So, I am not quite sure what to do.

**Comment by popcor255** [comment]
I fixed it. Big thanks. @michaelawyu

**Comment by sergetron** [comment]
The first guide in the "Getting Started" series, ["Overview of Tekton"](https://github.com/tektoncd/website/blob/master/content/en/docs/getting-started-overview.md), has been recently published!

**Comment by nikhil-thomas** [comment]
this is something we need to handle better for our users 🧑‍💻 
/remove-lifecycle rotten

**Comment by afrittoli** [comment]
Related https://github.com/tektoncd/pipeline/issues/3705

**Comment by geriom** [comment]
The [onboarding experience](https://tekton.dev/docs/getting-started/) for new users is a lot better now, with introductory videos and bite-sized friendly tutorials.

Closing this one.
