### ISSUE TITLE
Variable Substitutions

### ISSUE THREAD

**Issue by coryrc** [tektoncd/website#174]
Docs should say that when single quotes are used, even in the middle of a `script: |` block, that the substitution does not occur.

I would make a PR but I can't find the file and the "Edit this page" link doesn't work

**Comment by coryrc** [comment]
Oh wait, hmm, that's not my problem. Sorry.

**Comment by AlanGreene** [comment]
Variable substitution docs are at https://github.com/tektoncd/pipeline/blob/master/docs/variables.md

A PR to improve them / add clarity around behaviour would be very welcome 😸
