### ISSUE TITLE
Workspaces disable-affinity-assistant link is broken

### ISSUE THREAD

**Issue by NissesSenap** [tektoncd/website#177]
# Expected Behavior
The sentence: "The Affinity Assistant can be disabled by setting the **disable-affinity-assistant** feature gate to true.
It points to"
https://tekton.dev/docs/pipelines/install#customizing-basic-execution-parameters
Which is broken.

# Actual Behavior
https://tekton.dev/docs/pipelines/install#customizing-basic-execution-parameters gives: Not found

# Steps to Reproduce the Problem

1. curl https://tekton.dev/docs/pipelines/install#customizing-basic-execution-parameters
2.
3.

# Additional Info

**Comment by NissesSenap** [comment]
This might have something to do with: https://github.com/tektoncd/website/issues/177 but I don't know.

**Comment by AlanGreene** [comment]
This link currently points to https://github.com/tektoncd/pipeline/tree/master/install.md#customizing-basic-execution-parameters but the file is actually located at https://github.com/tektoncd/pipeline/tree/master/docs/install.md#customizing-basic-execution-parameters (note the missing `docs/`)

**Comment by afrittoli** [comment]
Thanks for reporting the issue. This will be fixed by #187
