### ISSUE TITLE
Improve the documentation landing page

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/website#195]
The landing page could use a few improvements:

- change the title to "Welcome to Tekton"
- expand more on the initial paragraph
  - inline part of the concepts page, add a diagram or two
  - we could add a list of projects with a one sentence description about each 
- the "what's next" does not seem to add much value, I would remove it
- rending of the TOC below seems broken, there is too much space between sections:

![image](https://user-images.githubusercontent.com/2205608/98000654-9f762080-1de4-11eb-91f7-51c5f11fad77.png)

**Comment by cclemonzy** [comment]
Hi afrittoli , and all , 
I think I can do this doc improvement. 

- change title from "Tekton Documentation" to "Welcome to Tekton"
- remove following parts only, but keep `Note`  section
`What’s next`
`To get started, read the contents below.`

and i want to  confirm about
- too much spaces between  Concepts and Dashboard  
now document site display `Tasks and Pipelines`, `Triggers and EventListeners`, `CLI `  between `Concepts` and `Dashboard`. 
so I think no more improvement need here, right?  or , maybe you mean spaces between every section is still too wide? 
-  to expand more information in intial paragraph
which part of content in concept section  do you perfer to link? if no, how about `overview` and  use pipeline diagram? 

thanks in advance

**Comment by cclemonzy** [comment]
and i will try to assign this issue to myself

/assign @cclemonzy

**Comment by afrittoli** [comment]
Thanks @cclemonzy - looking forward to your contributions!

**Comment by cclemonzy** [comment]
Hi, @afrittoli , @vdemeester and all.  I have done improvement in team repository and did a Pull Request #255  
 
But now it run into errors  at "Deploy failed" phase. [Deploy Logs](https://github.com/tektoncd/website/pull/255/checks?check_run_id=2092427013) .   

I looked up the logs and got message  says sth wrong with trigger sync
 `ERROR:root:No tag main found in <git.repo.base.Repo '/opt/build/repo/sync/.cache/triggers/.git'`

and I found there is a  [latest update for trigger branch](https://github.com/tektoncd/website/commit/bb25ab37bb9f7553cc77d2378449df47bbffc35e#diff-043f26172907c43017b56d84eca8d894137f5d84573a67838bb6fc2059a64b7e)  

I guess this failure seems to be related with this update, but I cannot have found the solution.
Should you have any suggestion, please let me know.  
Thanks in advance

**Comment by cclemonzy** [comment]
Hi, @afrittoli  we could not add one or two proper images on landing page now, I fell sorry for  theinconvenience.  And the other requirements here is done in PR #263 as discussed in PR conversation.

**Comment by AlanGreene** [comment]
This is done. Other improvements coming in #17 and other issues.
