### ISSUE TITLE
Getting Started: "tkn task start hello --dry-run" fails with "Error: task name hello does not exist in namespace default"

### ISSUE THREAD

**Issue by florath** [tektoncd/website#199]
# Expected Behavior
`tkn task start hello --dry-run`

should behave as described and output the taskrun resource description

# Actual Behavior

`tkn task start hello --dry-run`

logs

`Error: task name hello does not exist in namespace default`

# Steps to Reproduce the Problem

1. Use the provided ppa for Ubuntu to install the tkn binary
2. Install an up to date version of the tekton pipeline

# Additional Info

It looks that the binary in the ppa is (very) old and does not work with current tekton pipelines.

```
# tkn version
Client version: 2020-04-01T10:57:38Z
Pipeline version: unknown
```

After using an up-to date tkn binary, everything works fine

```
# tkn version
Client version: 0.13.1
Pipeline version: v0.17.3
```

Suggestion: Either update the version in the ppa or remove the section in flavor of using the package from github.

**Comment by AlanGreene** [comment]
tkn 0.13.1 does appear to be available in the ppa

Tested on Ubuntu 20.04 (Focal Fossa)

```
$ sudo add-apt-repository ppa:tektoncd/cli
...
$ sudo apt-get update
...
$ sudo apt-get install tektoncd-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  tektoncd-cli
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 8952 kB of archives.
After this operation, 42.4 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/tektoncd/cli/ubuntu focal/main amd64 tektoncd-cli amd64 0.13.1-0 [8952 kB]
...
```

However following the instructions on https://tekton.dev/docs/getting-started/ I get 0.8.0
Updating the instructions to use `focal` instead of `eoan` yields 0.13.1. Is this expected? Do we only ship newer tkn releases for `focal` or newer?  @chmouel @piyush-garg

**Comment by chmouel** [comment]
We only use what PPA gives us, I am not really sure how to make PPA generating for multiple distribution, so I guess the packages will only targets the latest LTS (which is focal)

I'll see if we can do some documentation update,

**Comment by chmouel** [comment]
Maybe we should use https://build.opensuse.org/ in the future, which seems more maintained and featurefull than launchpad.

**Comment by afrittoli** [comment]
So, is the issue only related to the version of `tkn`? Does it work fine with the latest `tkn`?

**Comment by chmouel** [comment]
@afrittoli yes should be fixed using the version from focal,
