### ISSUE TITLE
Repo docs are kinda sparse 😅

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/website#2]
We should add:

* CONTRIBUTING.md
* DEVELOPMENT.md
* Pull request + issue templates

We should probably have more in the README than we currently have:

![image](https://user-images.githubusercontent.com/432502/54318642-29380100-45a4-11e9-89f2-6a9638bc4643.png)

( 🤣 d is for @dlorenc )

**Comment by cizixs** [comment]
I believe many maintainers are waiting for `development.md` to anticipate.

**Comment by bobcatfish** [comment]
Sorry about this @cizixs , I've bumped this up our work queue! I definitely want to focus on getting the bare minimum docs into all of the tektoncd repos asap :)

**Comment by bryantbiggs** [comment]
any way I can help? I don't want to just start submitting various PRs for documentation but would love to help out if I can

**Comment by xomiamoore** [comment]
Still pretty sparse but I added a quick start guide (to help solve #3) here - https://github.com/tektoncd/website/pull/4

**Comment by bobcatfish** [comment]
Thanks @xomiamoore that's definitely a step in the right direction!
