### ISSUE TITLE
Section links next to titles

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/website#205]
### Feature request

Add links next to titles in all markdown pages.

### Use case

As a web site user I would like to be able to select and share a link to a specific section within a document.

Anchors are already defined in the page, and they're used for the TOCs at the top of many pages. However to share a link to a section today one have to look for the TOC or look at the source of the page.

A clickable link next to each section title, that points to the section itself via the fragment, would be really handy.

I see the link exists on other websites that use docsy (knative), so hopefully this is just a matter of configuration:

![image](https://user-images.githubusercontent.com/2205608/98561313-aac3c300-22a0-11eb-98bc-b2f260fc4ad8.png)

**Comment by moficodes** [comment]
I can look into that, if you havent already fixed it.

**Comment by mnitta** [comment]
I can handle this, if this is still an issue. @afrittoli

**Comment by afrittoli** [comment]
That'd be great, thank you!
