### ISSUE TITLE
Broken text in the event listener docs

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/website#211]
# Expected Behavior
The event listener docs are rendered correctly

# Actual Behavior
The text at the following link is broken:
https://tekton.dev/vault/triggers-master/eventlisteners/#how-does-the-eventlistener-work

The original document looks ok, so it's probably something related to the decoding of the text during sync:
https://github.com/tektoncd/website/blob/4677778c4503fb51d2ee5927e5ce40023fe36658/sync/sync.py#L189-L195

I wonder if we should put 'utf-8' first.

**Comment by afrittoli** [comment]
https://tekton.dev/vault/triggers-v0.9.1/eventlisteners/#how-does-the-eventlistener-work

**Comment by nikhil-thomas** [comment]
[](url)

> https://tekton.dev/vault/triggers-v0.9.1/eventlisteners/#how-does-the-eventlistener-work

This link is working for me 🤔

it fails for `master`. As `master` branch doesn't exist any more, this is expected isn't it.

This page is not there in `main` branch.

**Comment by afrittoli** [comment]
The link works fine, it's the text that is broken

![image](https://user-images.githubusercontent.com/2205608/118988545-31a4d700-b979-11eb-9b40-c2d3e8c04cdf.png)

**Comment by afrittoli** [comment]
On `main` I don't see that text anymore https://tekton.dev/vault/triggers-main/eventlisteners/#how-does-the-eventlistener-work this would be a fix on the old branch only. Not so critical then :)
