### ISSUE TITLE
TaskRuns -- markdown syntax fix needs backported or published

### ISSUE THREAD

**Issue by boweeb** [tektoncd/website#216]
# Expected Behavior

Here: https://tekton.dev/docs/pipelines/taskruns/#specifying-the-target-task

Code block ends with the example `spec`.
The next section "Tekton Bundles" is rendered as an actual section, not part of the code block.

# Actual Behavior

The content between the example `spec` code block, through the first code block under "Tekton Bundles" is rendered as one large code block.

# Steps to Reproduce the Problem

1. Go to live site: https://tekton.dev/docs/pipelines/taskruns/#specifying-the-target-task as of `Wed Nov 18 14:24:20 UTC 2020`

# Additional Info

Assuming [this](https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md) is the upstream source, this appears to have already been fixed here: https://github.com/tektoncd/pipeline/pull/3507

So either the website content needs refreshed or the change needs backported (the workflow is not clear).

https://github.com/tektoncd/website/issues/34 appears to be related.

**Comment by afrittoli** [comment]
Thanks for reporting this!

We now do nightly deploys.  Each deploy runs the sync script that pulls in the docs far various released versions as well as `master`.

The patch tektoncd/pipeline#3507 was merged 8 days ago, so it should be both on `v0.18.0` docs as well as on master docs, but I don't see it there, so something is going wrong.

**Comment by afrittoli** [comment]
It looks like this is not in v0.18.0 or v0.18.1 yet.

**Comment by AlanGreene** [comment]
This is fixed in the docs for v0.19.0 and later

/close
