### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by zapman449** [tektoncd/website#229]
# Expected Behavior
Text says:
```
Any of the above options will fetch the image using the ImagePullSecrets attached to the ServiceAccount specified in the PipelineRun. See the Service Account section for details on how to configure a ServiceAccount on a PipelineRun. The PipelineRun will then run that Task without registering it in the cluster allowing multiple versions of the same named Task to be run at once.
```

# Actual Behavior
`ServiceAccount` link leads to a 404 page.

# Steps to Reproduce the Problem

1. go to page https://tekton.dev/docs/pipelines/pipelines/
2. click link `Service Account` which points to https://tekton.dev/docs/pipelines/pipelines/pipelineruns.md#service-accounts (link is around 1/4 to 1/3rd the way down the page.)
3. receive 404

# Additional Info

**Comment by afrittoli** [comment]
Thank you for your report!

**Comment by kobaji** [comment]
Hi @afrittoli I am looking at this issue.

I think the link of  "Service Account" in the following file should be corrected.

https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md

> See the [Service Account](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#service-accounts) section

I strongly hope to fix this. Once I've understood which files I should fix aside from the above, I'll try this.
(Or if you would tell me whether any other files should be corrected, I could start correcting at once haha)

**Comment by afrittoli** [comment]
Hi @kobaji, thank you for looking into this!

If you clone the website repo on your laptop and run the  [sync](https://github.com/tektoncd/website/blob/master/sync/README.md) script locally, you will be able to run the website locally and try things out. See also our [development](https://github.com/tektoncd/website/blob/master/DEVELOPMENT.md#running-locally) guide. 

The sync script clones all the relevant repos locally into a cache folder, it then builds the website out of the clones. 
After the initial clone, you can make changes to your local cache and re-sync, it will rebuild the website with your local changes.
I should perhaps add this to the development guide ^_^

Regarding the specific issue, the fragment in "https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#service-accounts" seems to be wrong, I think the correct fragment should be #specifying-custom-serviceaccount-credentials .

I think there is a second issue besides the fragment: "https://tekton.dev/docs/pipelines/pipelines/pipelineruns.md" contains one `pipelines` too much, it should be "https://tekton.dev/docs/pipelines/pipelineruns.md" instead. There is no need for the original link to be absolute, it should be a relative link instead. Changing that might fix the issue.

Finally, it should be possible for the absolute link to be rendered correctly too though; there might be an issue in the sync script that causes this behaviour, but this is something that can be dealt with in a separate PR. If you are interested in looking into this part too I'd be happy to provide guidance if needed.

**Comment by kobaji** [comment]
Thank you very much for your kindness @afrittoli 
I'll be considering with my teammate and  within a few days able to declare that some of my teammate tries this issue

**Comment by afrittoli** [comment]
Great, thank you!

I found another case in the trigger docs. On the page "https://tekton.dev/docs/triggers/triggers/" the [interceptors](https://tekton.dev/docs/triggers/triggers/eventlisteners.md#interceptors) link is broken.

I checked the source docs again on both pipeline and triggers, and in fact the original link is relative, not absolute as I thought.
Apart from the issue with the fragment, this looks like an issue in the sync script then. 

If you want to try and tackle this, I would recommend writing a unit test that reproduces the issue first, and taking it from there.

**Comment by afrittoli** [comment]
I dig a bit more into this because it looked like it was more complex than it looked like on the surface.
Some links were not being transformed because the line was in a list and thus started with spaces. Since we parse the markdown line by line, without the context, the markdown parser considered the line as a code block, and ignored links.

Something like this seems to be working, but it would need some unit tests:
```
@@ -198,7 +202,11 @@ def decode(s, encodings=('utf8', 'latin1', 'ascii')):
 def transform_line(line, base_path, local_files, rewrite_path, rewrite_url):
     """ transform all the links in one line """
     line = line.rstrip()
-    links = get_links(line)
+    # We need to left strip lines before paring for links because
+    # reading the markdown line by line, the context is lost and line
+    # indented because of a list is otherwise considered as a code block
+    # Links are ignored in code blocks
+    links = get_links(line.lstrip())
     # If there are links in this line we may need to fix them
     for link in links:
         # link contains the text and href
```

**Comment by kobaji** [comment]
Thanks @afrittoli for the detail explanation.

I undestood the following parts are needed to be corrected.

https://github.com/tektoncd/website/blob/828371abc6577020f0faf6207ad10a47a2cfd6ec/sync/sync.py#L198
https://github.com/tektoncd/website/blob/a5ed52e79f2c4124b1df6a1a339005d90bff20ba/sync/test_sync.py#L260

I will let all you know if I or my teammate had a time to try this issue, unless someone else declare to try.

**Comment by afrittoli** [comment]
> I will let all you know if I or my teammate had a time to try this issue, unless someone else declare to try.

Thank you @kobaji - do you have any update on this?  I'd be happy for you or someone on your team to fix this. 
I'd like to fix the broken links in our website as soon as possible though, so if you're not able to work on this this week, I would propose a patch myself 🙏

**Comment by kobaji** [comment]
Thank you @afrittoli , could you please fix by yourself? Unfortunately we do not enough time on this week.
I apologize for not trying.

**Comment by afrittoli** [comment]
This is the fix on pipeline side: https://github.com/tektoncd/pipeline/pull/3773
