### ISSUE TITLE
error: unable to recognize "trigger-template.yaml": no matches for kind "TriggerTemplate" in version "triggers.tekton.dev/v1beta1"

### ISSUE THREAD

**Issue by mayank-sfdc** [tektoncd/website#231]
# Expected Behavior
kubectl apply -f trigger-template.yaml # should pass and resource must be created 
# Actual Behavior
Failed with the **error: unable to recognize "trigger-template.yaml": no matches for kind "TriggerTemplate" in version "triggers.tekton.dev/v1beta1"**
# Steps to Reproduce the Problem

1. kubectl apply -f  trigger-template.yaml 
2.
3.

# Additional Info

**Comment by AlanGreene** [comment]
Thanks for reporting this issue @mayank-sfdc. Can you provide more information about where in the documentation you found this?

The `apiVersion` for Triggers resources should be `triggers.tekton.dev/v1alpha1`

**Comment by AlanGreene** [comment]
I can't find any references to `triggers.tekton.dev/v1beta1` in the docs or examples so closing this.

@mayank-sfdc if you can point us to where you found that invalid value we can reopen the issue.

/close
