### ISSUE TITLE
Architecture image is broken in the "getting started" katacoda tutorial

### ISSUE THREAD

**Issue by stevemar** [tektoncd/website#246]
# Expected Behavior

The image should load

# Actual Behavior

The image does not load as it references a github _page_ rather than the image itself. See screenshots

<img width="1555" alt="Screen Shot 2021-02-16 at 3 26 02 PM" src="https://user-images.githubusercontent.com/4118756/108117831-77e15600-706b-11eb-925e-8ceffb40cb58.png">
<img width="594" alt="Screen Shot 2021-02-16 at 3 26 08 PM" src="https://user-images.githubusercontent.com/4118756/108117832-77e15600-706b-11eb-806b-9f35b8e3a2ec.png">

The markdown can be found [here](https://github.com/tektoncd/website/blob/main/tutorials/katacoda/getting-started/concepts.md) and reads:

```
![architecture](https://github.com/tektoncd/website/tree/main/tutorials/katacoda/getting-started/images/architecture.png?raw=true)
```

Instead, it should read:

```
![architecture](https://raw.githubusercontent.com/tektoncd/website/main/tutorials/katacoda/getting-started/images/architecture.png)
```

# Steps to Reproduce the Problem

1. Load this page: https://github.com/tektoncd/website/blob/main/tutorials/katacoda/getting-started/concepts.md

**Comment by stevemar** [comment]
I'm happy to submit a PR if folks are good with the suggested changes.

**Comment by afrittoli** [comment]
Nice catch, thank you!
A PR would be welcome, thank you!

**Comment by stevemar** [comment]
@afrittoli thanks, i'm finding a few other bugs / room for improvements in the tutorials, how would you like that feedback gathered?

**Comment by afrittoli** [comment]
> @afrittoli thanks, i'm finding a few other bugs / room for improvements in the tutorials, how would you like that feedback gathered?

A GitHub issue would be fine, but I'm happy with whatever works best for you.

Thank you!

**Comment by stevemar** [comment]
Thanks @afrittoli i'll run through one of the katacoda tutorials and gather some feedback for you. Here's the fixed link:

<img width="606" alt="Screen Shot 2021-02-19 at 9 54 44 AM" src="https://user-images.githubusercontent.com/4118756/108520347-91b3b080-7298-11eb-956a-2d4effe504b3.png">
