### ISSUE TITLE
DNS resolution for tekton.dev is broken in exotic ways

### ISSUE THREAD

**Issue by daenney** [tektoncd/website#253]
# Expected Behavior

tekton.dev can't be properly resolved in certain cases. This appears to be caused by the fact that tekton.dev has a CNAME at the apex pointing at tekton.netlify.com, but a CNAME at the apex is not allowed. 

# Actual Behavior

tekton.dev should resolve properly

# Additional Info

First, find who is responsible for `dev.` root
```
$ dig -t NS dev.

; <<>> DiG 9.16.12 <<>> -t NS dev.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31827
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;dev.				IN	NS

;; ANSWER SECTION:
dev.			21089	IN	NS	ns-tld2.charlestonroadregistry.com.
dev.			21089	IN	NS	ns-tld1.charlestonroadregistry.com.
dev.			21089	IN	NS	ns-tld4.charlestonroadregistry.com.
dev.			21089	IN	NS	ns-tld5.charlestonroadregistry.com.
dev.			21089	IN	NS	ns-tld3.charlestonroadregistry.com.
```

Using one of those, lets ask it about who the nameservers are for tekton.dev
```
$ dig -t NS @ns-tld2.charlestonroadregistry.com. tekton.dev.

; <<>> DiG 9.16.12 <<>> -t NS @ns-tld2.charlestonroadregistry.com. tekton.dev.
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39237
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 4, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tekton.dev.			IN	NS

;; AUTHORITY SECTION:
tekton.dev.		10800	IN	NS	dns1.p07.nsone.net.
tekton.dev.		10800	IN	NS	dns2.p07.nsone.net.
tekton.dev.		10800	IN	NS	dns3.p07.nsone.net.
tekton.dev.		10800	IN	NS	dns4.p07.nsone.net.
```

However, doing a regular recursive lookup for tekton.dev's NS records results in something peculiar:
```
$ dig -t NS tekton.dev

; <<>> DiG 9.16.12 <<>> -t NS tekton.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7778
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;tekton.dev.			IN	NS

;; ANSWER SECTION:
tekton.dev.		2699	IN	CNAME	tekton.netlify.com.
```

This is correct, in that if a CNAME exists for that name, DNS must only return that CNAME. But we asked for NS records. Things are now broken. This should not be the response to an NS lookup, instead it should look something like this:
```
$ dig -t NS google.dev

; <<>> DiG 9.16.12 <<>> -t NS google.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63214
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;google.dev.			IN	NS

;; ANSWER SECTION:
google.dev.		86400	IN	NS	ns2.googledomains.com.
google.dev.		86400	IN	NS	ns4.googledomains.com.
google.dev.		86400	IN	NS	ns3.googledomains.com.
google.dev.		86400	IN	NS	ns1.googledomains.com.
```

I suspect this is a misconfiguration of tekton.dev at NS1: https://help.ns1.com/hc/en-us/articles/360020248973-About-CNAME-ALIAS-and-linked-records

> CNAME
Use: | To implement simple indirection via referrals
Don't use: | The source is the zone apex, or when the target is in a different zone in NS1 and has an advanced configuration

> ALIAS
Use: | To achieve the same functionality as a CNAME record at the zone apex
Don't use: | Non-zone apex records

I believe tekton.dev is misconfigured at NS1, it appears to be configured with a CNAME at the apex, but it should be an ALIAS. I would also suggest reaching out to NS1, as letting someone configure a CNAME at the apex should not have been allowed in the first place.

**Comment by afrittoli** [comment]
Thanks @daenney for the report!
I replaced the CNAME record with an ALIAS, it looks better now:
```
$ dig -t NS tekton.dev

; <<>> DiG 9.10.6 <<>> -t NS tekton.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23280
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tekton.dev.			IN	NS

;; ANSWER SECTION:
tekton.dev.		3600	IN	NS	dns1.p07.nsone.net.
tekton.dev.		3600	IN	NS	dns2.p07.nsone.net.
tekton.dev.		3600	IN	NS	dns3.p07.nsone.net.
tekton.dev.		3600	IN	NS	dns4.p07.nsone.net.

;; Query time: 42 msec
;; SERVER: 194.168.4.100#53(194.168.4.100)
;; WHEN: Fri Mar 26 15:57:29 GMT 2021
;; MSG SIZE  rcvd: 196
```

Please let me know if you're happy to close this now.

**Comment by daenney** [comment]
Everything works for me now too. Thanks for fixing it!
