### ISSUE TITLE
[Question]: Could you please tell me how I can resolve the deploys' failures?

### ISSUE THREAD

**Issue by kobaji** [tektoncd/website#260]
Hi there,
I opened a PR #259 by mistake but I am wondering why this deploy failed.
As you can see in that PR>[Files changed](https://github.com/tektoncd/website/pull/259/files) , I just modified README.md in this PR, therefore I did not think it would fail.

[The Deploy log](https://app.netlify.com/sites/tekton/deploys/6062b3575dc1e700073ac1d2#L208) says as below but I am not sure how I can resolve this problem ( Can I add tag `main` into the `<git.repo.base.Repo '/opt/build/repo/sync/.cache/pipeline/.git'>`? If so, how can I add it? )

> ERROR:root:No tag main found in <git.repo.base.Repo '/opt/build/repo/sync/.cache/pipeline/.git'>

I could not find the documents regarding this problem.
This must be helpful for my fellows and me to promote our contributions for tektoncd/website.
Thank you.

**Comment by AlanGreene** [comment]
@afrittoli do we need to clear the netlify build cache or something since the recent branch renaming? Looks like it's getting stuck on the sync script. I reproduced the same error as @kobaji in a PR based off latest commit on `main` https://github.com/tektoncd/website/pull/261 (logs https://app.netlify.com/sites/tekton/deploys/60631fc36a06700008b6fddc)

**Comment by afrittoli** [comment]
We rely on Netlify for the CI jobs, and they take the `branch-a` and build from there.
They also use a cache to improve the runtime of the CI jobs.

The issues you're seeing are related to the change of the default repo branch from `master` to `main` across all Tekton repos, which is something that should not happen again in future.

I will clean the Netlify cache, that should solve the issue.

**Comment by afrittoli** [comment]
Oh, the PR is closed now. If this happens again please ping me on the PR, I will reset the Netlify cache.

**Comment by AlanGreene** [comment]
@afrittoli I reopened https://github.com/tektoncd/website/pull/261 since this is something that'll affect the next person to open a PR

**Comment by afrittoli** [comment]
Thanks. We don't really control how Netlify uses their caches, I've cleaned the cache a few times, so I would expect CI jobs to work now, but perhaps they have a cache per node or something like that...

**Comment by AlanGreene** [comment]
Looks like we're good now, all checks passed on that PR. Thanks Andrea 😸

**Comment by kobaji** [comment]
> We rely on Netlify for the CI jobs, and they take the branch-a and build from there.
They also use a cache to improve the runtime of the CI jobs.

Thank you very much for your help @afrittoli , @AlanGreene 

I reopened PR #259 and newly created PR #262 but neither of them succeeded their deploys.

> We don't really control how Netlify uses their caches, I've cleaned the cache a few times, so I would expect CI jobs to work now, but perhaps they have a cache per node or something like that...

Honestly I am not sure if what I have done in the above PRs, but do we need to re-clean the cache?

**Comment by cclemonzy** [comment]
@afrittoli  @AlanGreene @kobaji  My new created PR #263 got the same build failure, so I think I should reopen this issue instead of creating new issue.  As what described in (https://github.com/tektoncd/website/issues/260#issuecomment-810958424),  no more action is required in the source branch? or anything we can do for cleaning the cache?

**Comment by AlanGreene** [comment]
@kobaji @cclemonzy It looks like the checks are passing on https://github.com/tektoncd/website/pull/263 now. Are we OK to close this?

**Comment by kobaji** [comment]
Thank you very much @AlanGreene for your kindness.
Yes we can close this issue and I will.

As I mentioned in [the previous comment](https://github.com/tektoncd/website/issues/260#issuecomment-811536266), some PRs have not been succeeded their deploys.

> I reopened PR #259 and newly created PR #262 but neither of them succeeded their deploys.

But these PRs are just for test therefore I will no more check or ask about the failures.
Once we have open another PR and the deploy did not succeed, let us ask you or @afrittoli 

Thank you!!
