### ISSUE TITLE
Trigger Templates Typo

### ISSUE THREAD

**Issue by jenoOvchi** [tektoncd/website#268]
In the pargraph "To enable support for arbitrary resource types, the resource templates are internally resolved as byte blobs. As a result, validation on these resources is only done at event processing time (rather than during TriggerTemplate creation). :rotating_light: As of now, only Tekton resources can be defined within a TriggerTemplate :rotating_light:" rotating_light are not applyed to the last sentence.

**Comment by afrittoli** [comment]
@jenoOvchi thank you for the issue report and sorry about the late reply.
Could you please include a link to the page where you see the issue?

**Comment by afrittoli** [comment]
Never mind - found the issue in https://tekton.dev/vault/triggers-v0.9.1/triggertemplates/

From [hugo docs](https://gohugo.io/getting-started/configuration/#enableemoji), it looks like hugo can supports this syntax, but it may need to be enabled, as it's disabled by default.

**Comment by AlanGreene** [comment]
Looks like https://tekton.dev/docs/triggers/triggertemplates/ but that content was removed / rewritten in https://github.com/tektoncd/triggers/pull/981.

Do we need to go back and fix this in previous versions? Also should we be using this emoji syntax or actual unicode emoticons instead?

**Comment by afrittoli** [comment]
> Looks like https://tekton.dev/docs/triggers/triggertemplates/ but that content was removed / rewritten in [tektoncd/triggers#981](https://github.com/tektoncd/triggers/pull/981).
> 
> Do we need to go back and fix this in previous versions? Also should we be using this emoji syntax or actual unicode emoticons instead?

I'm not sure we need to go back and fix things as old as `v0.9.1` - however since hugo supports the emoji syntax with colons `:<name>:` we could enable it anyways - I tried it locally and it works fine.
