### ISSUE TITLE
Latest Versions stuck on v0.10.1 for triggers

### ISSUE THREAD

**Issue by seankhliao** [tektoncd/website#273]
# Expected Behavior

"Latest Versions" in navbar reflects latest released versions

# Actual Behavior

Triggers still shows v0.10.1 when the latest is v0.14.1

![2021-05-23-201258](https://user-images.githubusercontent.com/11343221/119394244-3f888e00-bcd2-11eb-8378-5d412ed6f300.png)

# Steps to Reproduce the Problem

* go to https://tekton.dev/docs/
* click "Latest Versions" in navbar

**Comment by AlanGreene** [comment]
Thanks for reporting. There's a PR open to add the missing versions https://github.com/tektoncd/website/pull/270

**Comment by AlanGreene** [comment]
Latest versions of Triggers docs are now available
