### ISSUE TITLE
Add Tekton robotic cat (in color) image to tekton.dev

### ISSUE THREAD

**Issue by anneqm** [tektoncd/website#28]
# Expected Behavior
We want to see the familiar colored robotic cat image similar to the sticker available from cd.foundation or the image currently on the existing tekton.dev site

# Actual Behavior
The only robotic cat is a very tiny white on black version in the masthead. 

# Additional Info
See https://cd.foundation/projects/ and https://tekton.dev/ for images requested.

**Comment by popcor255** [comment]
I know @skaegi did this. I can't find the pr :thinking: 
@anneqm is this issue resolved?
