### ISSUE TITLE
Should `dpkg` be used to install the `.deb` package of the CLI

### ISSUE THREAD

**Issue by tpiperatgod** [tektoncd/website#281]
I was following to the [CLI-Installation](https://tekton.dev/docs/cli/#installation) documentation for installing Tekton's CLI and I found that the documentation said.

>Debian, Ubuntu, and other deb-based distros
>Find the .deb package of the tkn release you would like to install on the tkn Releases page and install it with
>```
># Replace LINK-TO-THE-PACKAGE with the package URL you would like to use.
>rpm -Uvh LINK-TO-THE-PACKAGE
>```

# Expected Behavior
Should `dpkg` be used to install the `.deb` package?
I noticed that there is a PR(#244) that fixes a similar issue and suggest that the same treatment should be applied here.  

# Actual Behavior
The documentation prompts to use `rpm` to install the `.deb` package

# Steps to Reproduce the Problem

1. Reference document [CLI-Installation](https://tekton.dev/docs/cli/#installation)

# Additional Info
No more

Thx.

**Comment by AlanGreene** [comment]
Thanks for reporting this @tpiperatgod, it does look like it should be using `dpkg` as in the change you referenced. @tektoncd/cli-maintainers fyi

The content for that doc is at https://github.com/tektoncd/cli/tree/main/docs so it would need to be updated there.

**Comment by tpiperatgod** [comment]
It looks like it will be fixed soon and I am closing it here.
