### ISSUE TITLE
Tasks section references broken URLs

### ISSUE THREAD

**Issue by thecooldrop** [tektoncd/website#285]
# Expected Behavior
Under section https://tekton.dev/docs/pipelines/tasks/#using-variable-substitution two pages are referenced, where user should be able to see complete list of available variable substitutions and list of fields which accepts substitutions, but there URLs lead to 404 pages.

![image](https://user-images.githubusercontent.com/17129522/126062829-3cd54327-40ed-4f5e-ad49-19e67b4319cf.png)

# Steps to Reproduce the Problem

1. Go to https://tekton.dev/docs/pipelines/tasks/#using-variable-substitution
2. At the end of sub-section locate the URLs pointing to *complete list of variable substitutions for Tasks* and * list of fields that accept substitutions*
3. Click on URLs
4. Observe the 404 error pages.

**Comment by AlanGreene** [comment]
Thanks for reporting this. Closing as a duplicate of https://github.com/tektoncd/website/issues/279
