### ISSUE TITLE
EventListener not Show URL Address.

### ISSUE THREAD

**Issue by maktup** [tektoncd/website#292]
# Expected Behavior
Problem to generate the ADDRESS URL with EventListener in TEKTON.

# Actual Behavior

# Steps to Reproduce the Problem
Here are:
https://github.com/wolfmanx23/cliente-api-kube/blob/master/pipeline/guia_ejecucion_comandos.txt
 
But never get the URL in EventListener whtn
$ oc get el -n pipelines-tutorial

With this and with other tutorials.

# Additional Info

**Comment by afrittoli** [comment]
Hello @maktup - thank you for your report.

The address of event listeners is displayed correctly when using `tkn` or `kubectl`. 
I'm not sure if there is an issue with the openshift client specifically, or if the address is missing for some reason.
You could try fetching the resource using `kubectl get -o yaml el/<name> -n pipelines-tutorial` to see if the address is in there at all.

If the URL is not there you could try reporting an issue to the triggers project, or chatting in the #triggers channel on slack. If the URL is there,  but not displayed by the `oc` client, you could report an issue to the openshift client directly https://github.com/openshift/oc - please specify the version of client and server that you're using.

I'm going to close this one for now as it does not apply to the tekton website or tekton documentation. 
Feel free to reopen should you have further questions.
