### ISSUE TITLE
Git resource for private repos doc approach

### ISSUE THREAD

**Issue by bigfleet** [tektoncd/website#293]
# Expected Behavior

Tekton triggers example uses a git resource for its public repo, creating an impression in the newcomer that this is how git repos are acquired.  (Not wholly incorrect, it seems.)

[Git resource](https://tekton.dev/docs/pipelines/resources/#git-resource) mentions nothing about private repos.

Cloning private repos is [relatively well documented](https://hub.tekton.dev/tekton/task/git-clone) elsewhere, so perhaps that document can be referenced here.

# Actual Behavior

No mention of private repos other than a [PullRequest](https://tekton.dev/docs/pipelines/resources/#pull-request) subsection.

# Steps to Reproduce the Problem

1. Forget everything that you know about tekton.
2. Visit above links.

# Additional Info

**Comment by bigfleet** [comment]
I do see that this link I've provided is a task from the catalog rather than something that ships out of the box with Tekton.  Hmm, makes fixing this a little more complicated possibly.

**Comment by AlanGreene** [comment]
Auth for PipelineResources is documented in https://tekton.dev/docs/pipelines/auth/
Does this cover the information you're looking for?

Also bear in mind that PipelineResources are effectively deprecated and there's an open TEP to make this official: https://github.com/tektoncd/community/pull/480

**Comment by bigfleet** [comment]
I didn't know that about PipelineResources, not even a whiff.  I also didn't get a clear picture from that link about what will be its replacement?  (Today's documentation does assert the criticality of acquiring source and pushing images, both of which seem currently to be PipelineResource responsibility.)  Their deprecation seems like it will be quite the event.  (I've been looking at Tekton seriously for about six weeks, so the project may very well be better off without their interface or implementation, I simply wouldn't know.)

I am happy to help write docs if I can understand what is going on in the first place.  :-D

The pipelines auth doc that you link does handle the canonical case.  It seems that the specific task I'm citing builds an alternative path (streamlined a bit).  I think it's reasonable to mention the items that are in flux in the documentation, but perhaps this ticket might not even been handled until some of it is settled.
