### ISSUE TITLE
The Rabbit in the Tekton and friends logo is barely visible 

### ISSUE THREAD

**Issue by Preeticp** [tektoncd/website#30]
# Expected Behavior
The logo with Tekton friends should be clearly visible.
# Actual Behavior
The rabbit in the logo is barely visible as the purple/blue color with the black background makes it difficult to see.
# Steps to Reproduce the Problem
See here: https://deploy-preview-24--tekton-dev.netlify.com/

Note: Strangely when you take a screenshot the rabbit gets highlighted but that's not what you see normally. Attaching a screenshot anyways.
![Screenshot from 2020-02-19 19-09-38](https://user-images.githubusercontent.com/16647625/74839829-f5389480-534b-11ea-9de5-c6a211b444fb.png)

**Comment by popcor255** [comment]
This was fixed in https://github.com/tektoncd/website/pull/107
