### ISSUE TITLE
Pipeline Metrics

### ISSUE THREAD

**Issue by cugykw** [tektoncd/website#309]
# Expected Behavior
https://tekton.dev/docs/pipelines/metrics/
__observability configuration__
Click on the jump link to a valid website.

# Actual Behavior

# Steps to Reproduce the Problem
__observability configuration__
The link on the official website is invalid.

# Additional Info

**Comment by afrittoli** [comment]
Thank you @cugykw for reporting this issue. 
This will be fixed by https://github.com/tektoncd/website/pull/314

**Comment by afrittoli** [comment]
Verified this is fixed now.
