### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by ionir-cloud** [tektoncd/website#313]
# Expected Behavior

More examples links will lead to the right github location

_More examples
See the following in-depth examples of configuring Workspaces:

Workspaces in a TaskRun
Workspaces in a PipelineRun
Workspaces from a volumeClaimTemplate in a PipelineRun_

# Actual Behavior
links are dead

# Steps to Reproduce the Problem

1. just click it
2.
3.

# Additional Info

**Comment by afrittoli** [comment]
Thank you for your report @ionir-cloud !
The broken links look like https://github.com/tektoncd/pipeline/tree/origin/release-v0.29.x/examples/v1beta1/taskruns/workspace.yaml .
The issue originates from having the `origin/release-v0.29.x/` in the sync configuration.
Previously we would only use tag names, but that did not allow for updates to the docs.
This will require a change in the sync script.
