### ISSUE TITLE
Add Dashboard Tutorial to the Website

### ISSUE THREAD

**Issue by ncskier** [tektoncd/website#32]
# Expected Behavior
I expect the website's [tutorial page](https://tekton-website-258208.firebaseapp.com/try/) to have a tutorial for using the Dashboard.

Based on a discussion in the Docs & Website meeting, I created a Tekton Dashboard tutorial in Katacoda: https://www.katacoda.com/ncskier/scenarios/tekton-dashboard. The intent of this tutorial is to have the website's `Monitor with Tekton dashboard` tutorial link to my Katacoda tutorial.

Please let me know if there are any updates/improvements I should make to my Katacoda tutorial; for example, to improve consistency across tutorials.

# Actual Behavior
The `Monitor with Tekton dashboard` tutorial does not link to anything.

# Additional Info
FYI
@bobcatfish 
@michaelawyu

**Comment by anneqm** [comment]
@vdemeester May we please also get a beta label on this one?  Thank you!

**Comment by bobcatfish** [comment]
🤔

**Comment by vdemeester** [comment]
https://prow.tekton.dev/command-help to know what are those commands :angel: :stuck_out_tongue:
