### ISSUE TITLE
Chains documentation on the Tekton website

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/website#320]
### Feature request

We would like to have the chains documentation available on the website.

### Use case

Software supply chain security gets a lot of attention from our user community now, it would be good to have the documentation of Tekton chains as part of the docs on the website to make the more discoverable.

### Notes

From website POV this should only require adding the sync config file. 
There may be changes required in the docs on chains side to add / adjust front matter or documents in general.

**Comment by priyawadhwa** [comment]
This would be awesome! @afrittoli did you want to add it in? I can open a PR otherwise :)

**Comment by afrittoli** [comment]
Thanks! I'm happy to create a PR.

**Comment by afrittoli** [comment]
I started working on a PR, and I noticed that there is no [front-matter](https://gohugo.io/content-management/front-matter/) in the docs.

@priyawadhwa cou you add front matter (see an [example](https://raw.githubusercontent.com/tektoncd/pipeline/main/docs/README.md)) to the docs you'd like to be published?

I can  also make some PRs to chains if you'd  prefer so.

**Comment by afrittoli** [comment]
https://github.com/tektoncd/website/pull/322

**Comment by afrittoli** [comment]
This is fixed now
