### ISSUE TITLE
"Getting Started with Tekton" Katacoda tutorial doesn't work

### ISSUE THREAD

**Issue by HildaHay** [tektoncd/website#321]
The pipeline execution always fails on "step-pytest".

Also, the Katacoda Editor doesn't open so any code editing has to be done via Vim or such.

**Comment by AlanGreene** [comment]
Thanks for reporting this @HildaHay. It looks like the sample app isn't compatible with python 3.10, pinning the image used in the build step to 3.9 allows it to pass. I've opened a PR with this change: https://github.com/tektoncd/website/pull/326
