### ISSUE TITLE
Incorrect list style in page of Configuring Interceptors

### ISSUE THREAD

**Issue by JohnNiang** [tektoncd/website#323]
# Expected Behavior
![image](https://user-images.githubusercontent.com/16865714/142580779-c4585d43-f488-4691-8a95-12397a7e44b1.png)
> https://github.com/tektoncd/triggers/blob/main/docs/interceptors.md#overview

# Actual Behavior
![image](https://user-images.githubusercontent.com/16865714/142580879-f56f8ac9-7cf6-401d-aaee-23a0d163667b.png)
>https://tekton.dev/docs/triggers/interceptors/#overview
# Steps to Reproduce the Problem

Redirect to https://tekton.dev/docs/triggers/interceptors/#overview

# Additional Info

Correct style in https://github.com/tektoncd/triggers/blob/main/docs/interceptors.md#overview.

**Comment by AlanGreene** [comment]
@afrittoli I think you may have referenced the wrong issue in PR #324, reopening this as it's still valid.

**Comment by AlanGreene** [comment]
@tektoncd/triggers-maintainers fyi

**Comment by binkkatal** [comment]
@AlanGreene , would like to contribute on this

**Comment by AlanGreene** [comment]
Thanks
/assign @binkkatal
