### ISSUE TITLE
Is there any plan to provide  Chinese translation in website

### ISSUE THREAD

**Issue by yuzp1996** [tektoncd/website#329]
Hi, I want to do some contributions about providing Chinese translation that developers can read the document in Chinese. 

But I don't know how to start that. 

Is it OK if I make a pullrequest directly?

**Comment by AlanGreene** [comment]
@yuzp1996 thanks for opening the issue. We're not currently planning to provide translations for the website / docs content. See https://github.com/tektoncd/website/pull/266#issuecomment-959781103 for more details.

**Comment by yuzp1996** [comment]
Thanks for your reply very much @AlanGreene
