### ISSUE TITLE
Lower bar for contributions: add generated preview links to website PRs

### ISSUE THREAD

**Issue by abrennan89** [tektoncd/website#331]
### Feature request

The bar seems very high for simple docs contributions: https://github.com/tektoncd/website/blob/main/DEVELOPMENT.md

I am pretty sure I have all of these tools installed, but to make sure I would need to go and find verification steps for each, since these aren't listed. I'd also need to go to each individual site to get install instructions if I didn't have any of the tools, rather than just a Getting Started type page that provides steps, or maybe a setup script.

There are also no minimum versions listed, so it's not clear if I would need to update things like Hugo where I may have an older version.

Rather than needing to do all this, it would be nice if I could just open a PR that generates a link to a netlify preview automatically.

### Use case

As a new contributor to Tekton, I would like to easily be able to open a docs preview, without having to spend a lot of time setting it up locally.

**Examples**

- Knative docs: https://github.com/knative/docs/pull/4539#issuecomment-985627948
- OpenShift docs: https://github.com/openshift/openshift-docs/pull/39410#issuecomment-983541390

**Comment by AlanGreene** [comment]
We do have Netlify preview links on PRs already, see for example this PR: https://github.com/tektoncd/website/pull/298

![image](https://user-images.githubusercontent.com/2829095/144647041-6bcf60f2-4a29-4aec-a53f-f168a82eec8c.png)

Clicking the 'Details' link brings you to the Netlify preview deployment, for that PR it's https://deploy-preview-298--tekton.netlify.app/

We used to have instructions for running locally using `netlify dev` but I'm not sure why that was removed.

Definitely agree about needing some central place for prereqs (including versions) to help folks get up and running with the website quickly.

**Comment by afrittoli** [comment]
> Thanks for raising this issue @abrennan89, I agree that we could make the instructions clearer and the process more straightforward to help folks get up and running quickly. Having a handy reference of any prereqs (including versions) in one place would be a start.
> 
> We do have Netlify preview links on PRs already, see for example this PR: #298
> 
> ![image](https://user-images.githubusercontent.com/2829095/144647041-6bcf60f2-4a29-4aec-a53f-f168a82eec8c.png)
> 
> Clicking the 'Details' link brings you to the Netlify preview deployment, for that PR it's https://deploy-preview-298--tekton.netlify.app/
> 
> We used to have instructions for running locally using `netlify dev` but I'm not sure why that was removed, maybe we could revisit that.

I think the instructions are still there? Maybe we could push them up in the page and move the "docker compose" approach lower in the list.

**Comment by geriom** [comment]
We have a doc that covers how to run the site locally either installing the necessary dependencies or using docker compose. https://tekton.dev/docs/contribute/run-locally/

Maybe we can simplify the [contributions landing page](https://tekton.dev/docs/contribute/) to make it more succinct and add clear instructions on how to preview your PR.
