### ISSUE TITLE
Automatically sync docs from Tekton repos to Website

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/website#34]
# Expected Behavior

Changes to the docs of a Tekton repo such as Pipeline should be reflected in the Website as soon as possible.

# Actual Behavior

At the moment we have a script that syncs docs from a fork of Pipeline. The script expects a special table at the top of docs and during the initial review of the website this was deemed as a bit of an ugly addition given that it only served the syncing script.

TODO(sbwsg): Update this issue with details of the script and the table that's needed.  Link to any PR discussion that was added around this.

**Comment by bobcatfish** [comment]
I've removed "beta blocking" from this b/c we can just do #37 and tackle this post beta.

**Comment by wlynch** [comment]
/assign wlynch

I'm going to start working on automating the sync here. I'll focus on just the automation pipeline, this way I don't get in the way of any work being done with sync configs.

**Comment by wlynch** [comment]
## Tentative Plan:

I'm assuming we will want to use Tekton for managing deployments.

1. Make [sync](https://github.com/tektoncd/website/tree/master/sync) its own dedicated image (mainly for dependency caching).
  To start this will be managed independently of doc deploys. Unsure if we want to keep this as an uncoupled dependency or tie it in as part of the deploy pipeline.
2. Create a Task that runs the sync image.
3. Create a Pipeline that pulls in multiple repos and runs sync.

**Comment by bobcatfish** [comment]
I think @afrittoli has been looking into this?

**Comment by popcor255** [comment]
I think this might be a different issue. For a doc to be rendered to website it must include the correct metadata. It might make sense to include this metadata on the config file itself. So, there is central place to modify it.

**Comment by bobcatfish** [comment]
Definitely something we still want, afaik we still need to sync the docs manually (is that right @afrittoli @popcor255 ?)

/lifecycle frozen

**Comment by afrittoli** [comment]
The sync happens automatically now, at deploy time. We deploy nightly.
However the latest fixes will show up on the master version of docs only.
We don't have a way to fix versioned documentation other than making a new minor release.

Also when a new release is created by a project, it has to be added to the config. There is a script for that, but someone has to run the script and make a PR. We could try to automate the PR creation as part of the release process.

**Comment by AlanGreene** [comment]
Sync updated to use release branches to avoid need for minor/patch releases to update docs. Closing this.
