### ISSUE TITLE
Update Katacoda Scenarios

### ISSUE THREAD

**Issue by kranurag7** [tektoncd/website#345]
- In the katacoda scenarios we need to update the scenario.
- `tekton-dashboard` service is missing in the `tekton-pipelines` namespace. The dashboard is not loading in the katacoda scenarios.
- https://katacoda.com/tektoncd/scenarios/dashboard
![tektoncd](https://user-images.githubusercontent.com/81210977/153822597-ef3e4da3-e349-497c-a9b0-850fc90a1905.jpg)
@AlanGreene Please let me know if I can help in updating the katacoda scenarios.

**Comment by AlanGreene** [comment]
Thanks for reporting this @kranurag7. I just tried it myself and it appears to be working correctly.

![image](https://user-images.githubusercontent.com/2829095/153853376-87359578-b480-436b-9224-5b989d6bc68d.png)
![image](https://user-images.githubusercontent.com/2829095/153853393-083ed9b7-e6ab-44cd-99be-4a6c434aa3f9.png)

Can you confirm that you successfully completed the 'Install the Tekton Dashboard' step and that the pods had started successfully? Were there any errors output as part of the install?

**Comment by kranurag7** [comment]
Thank you @AlanGreene for helping me out. It's working now. I think there was mistake from my side during installation.
