### ISSUE TITLE
Katacoda scenario Using Tekton Tasks no longer works

### ISSUE THREAD

**Issue by vovtz** [tektoncd/website#347]
# Expected Behavior
Starting the TaskRunner will result in a successful run

# Actual Behavior
The `pytest` fails, because the version used is incompatible with Python 3.10

# Steps to Reproduce the Problem

1. Complete the Using Tekton Tasks scenarion on Katacoda
2.
3.

# Additional Info

- Kubernetes version:
N/A
  **Output of `kubectl version`:**
N/A
  ```

- Tekton Pipeline version:

N/A

**Comment by AlanGreene** [comment]
Fix is live on katacoda and working as expected, thanks for reporting and providing the fix
/meow
