### ISSUE TITLE
Katacoda scenario Using Tekton Tasks doesn’t work with Python 3.10

### ISSUE THREAD

**Issue by vovtz** [tektoncd/website#349]
# Expected Behavior
Scenario can be completed with Python 3.10
# Actual Behavior
The tests by `pytest` fail
# Steps to Reproduce the Problem

1. Start the Using Tekton Task scenario
2. Follow the instructions (not specifying Python image tag results in version 3.10 used) OR specify the `3.10` tag manually
3. Apply the TaskRunner

# Additional Info

- Kubernetes version:
N/A

- Tekton Pipeline version:

N/A

**Comment by AlanGreene** [comment]
Sticking with python 3.9 as discussed on https://github.com/tektoncd/website/pull/350
