### ISSUE TITLE
Audit and update tutorials

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/website#36]
# Expected Behavior

* Tutorials at the "try" link at https://tekton-dev.netlify.com/ should be accurate representations of how to use Tekton Pipelines.
* These tutorials should use `v1beta1` Tekton Pipelines resources

# Actual Behavior

* The tutorials use `v1alpha1` resources at https://github.com/michaelawyu/tekton-examples
* Some of the tutorials aren't quite correct, e.g. the pipelines tutorial runs the two tasks in parallel and the built image is not used in the deploy

**Comment by stevemar** [comment]
👋 first time contributor here and hoping to help! Figured this would be a good place to start :) 

A had a few questions/comments:

1. Can someone confirm that the instructions that need updating exist here: https://github.com/ncskier/katacoda/tree/master/tekton-dashboard (they're then exposed at https://tekton.dev/try/)
1. Is there any desire to move those instructions to this repo so the folks here have more control over modifying them?
1. The link in the original issue 404s and should be updated to https://tekton.dev/try/
