### ISSUE TITLE
Exposing Event Listeners Externally

### ISSUE THREAD

**Issue by georgettica** [tektoncd/website#360]
# Expected Behavior
opening the link should point to a valid url that will give info on the provided issue

# Actual Behavior
clicking in https://tekton.dev/vault/triggers-v0.6.1/exposing-eventlisteners/#using-openshift-route the link goes to a broken link

# Additional Info
Add a cron to check validity of URL's in this repo

**Comment by AlanGreene** [comment]
@georgettica thanks for reporting the issue. The docs link you provided is for a very old release of Triggers (v0.6.1 release July 2020).

Assuming the broken link you're talking about is the one to further information about the OpenShift Routes.

The latest version of the EventListener doc is available at https://tekton.dev/docs/triggers/eventlisteners/#exposing-an-eventlistener-outside-of-the-cluster and points at more recent OpenShift resources which are still available.

**Comment by georgettica** [comment]
Hmm, didn't notice this was an old release, sorry!
