### ISSUE TITLE
Triggers and EventListeners documentation - TriggerFlow do not display

### ISSUE THREAD

**Issue by fckbo** [tektoncd/website#365]
# Expected Behavior
1. When accessing https://tekton.dev/docs/triggers/
2. At the end of the "How does Triggers work?" section a TriggerFlow diagram should display

# Actual Behavior
The TriggerFlow diagram does not display

# Steps to Reproduce the Problem
See expected Behavior section above

# Additional Info
The html artefact coresponding to the error
```
<img src="../images/TriggerFlow.svg" alt="TriggerFlow">
```

**Comment by AlanGreene** [comment]
fyi @binkkatal this issue looks like a duplicate of https://github.com/tektoncd/website/issues/340
See some of the work that has already be done for that issue

**Comment by binkkatal** [comment]
@AlanGreene , will verify and post and update

**Comment by vovtz** [comment]
It still looks like this 😞:

![image](https://user-images.githubusercontent.com/1536228/181715217-c66aa934-9859-4d18-8803-9a1a91c8904d.png)

**Comment by binkkatal** [comment]
@vovtz , still needs to cover up some test cases

**Comment by vovtz** [comment]
@binkkatal Who needs to do that?

**Comment by binkkatal** [comment]
@vovtz  i am working on it, did some changes in https://github.com/in2tivetech/tekton-website/commit/5cfe97f15c811fdf197cd72a6f4efbaf4dfae3a9 , need to check up against some test cases.
