### ISSUE TITLE
Remove references to Katacoda tutorials

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/website#366]
As discussed in the Docs WG on March 15th and on Slack (most recently https://tektoncd.slack.com/archives/CQYFEE00K/p1650380309062539) we have decided to remove references to the Katacoda tutorials from the website and docs.

Creating this issue to capture further discussion and track the work. This issue supersedes https://github.com/tektoncd/website/issues/310 and similar issues.

These are the places I've found where we currently link to a Katacoda scenario:

- [ ] tekton.dev home page
  - [ ] 'Get started with interactive tutorials' which links to https://tekton.dev/try/
    ![image](https://user-images.githubusercontent.com/2829095/164284553-e31901ec-7071-46c1-b3bb-5ed12d9f2d7a.png)
    - Update the link text to: 'Get started with Tekton.'
    - Update the URL to point to our new tutorial: `https://tekton.dev/docs/getting-started/`
  - [ ] 'Try Tekton' block towards the bottom of the page which links to the Katacoda playground scenario
    ![image](https://user-images.githubusercontent.com/2829095/164284960-3f5395e8-4a22-4f29-91ec-c5002cf84ad4.png)
    - Update the text to: 'Learn, explore, and experiment with Tekton by following the tutorial.'
    - Make the word 'tutorial' a link with URL pointing at `https://tekton.dev/docs/getting-started/`
- [ ] 'Try' link in the site header which also links to https://tekton.dev/try/
  - remove the link, page, and associated content
- [x] Dashboard repo: main readme, install docs, and the draft replacement for the Dashboard page on the website. Tracking this in https://github.com/tektoncd/dashboard/issues/2341

Some previous links have already been removed as part of recent updates to the docs.

~~Should we link to the new [Getting Started](https://tekton.dev/docs/getting-started/) tutorial in some of these locations instead? e.g. the 2 locations on the home page~~ (details above)

**Comment by binkkatal** [comment]
@AlanGreene would like to contribute

**Comment by AlanGreene** [comment]
@binkkatal thanks for joining the Docs WG today. I've updated the description with the details we discussed. Feel free to reach out here or on Slack if you have any questions.

/assign @binkkatal

**Comment by AlanGreene** [comment]
@binkkatal fyi, I found 1 more reference to the Try page and opened a PR to address it here: https://github.com/tektoncd/website/pull/372
