### ISSUE TITLE
released CLI docs still instruct to `brew tap`

### ISSUE THREAD

**Issue by dudash** [tektoncd/website#369]
# Expected Behavior
Docs should just say to `brew install tektoncd-cli`

# Actual Behavior
Docs say to: 
```
brew tap tektoncd/tools
brew install tektoncd/tools/tektoncd-cli
```

# Steps to Reproduce the Problem
1. Goto here: https://tekton.dev/docs/cli/
2. See the incorrect steps

Screenshot 2022-04-26
<img width="1680" alt="Screen Shot 2022-04-26 at 4 22 51 PM" src="https://user-images.githubusercontent.com/116840/165386633-564f5e4a-b41c-4280-9e54-399c3367d6f2.png">

# Additional Info
Looks like things are correct in github, so maybe this is something with the publishing process or automation?
Also, this is related to [cli issue here](https://github.com/tektoncd/cli/issues/683) which could probably be closed when this is resolved

**Comment by AlanGreene** [comment]
Thanks for reporting this @dudash. It looks like the docs were updated to remove reference to the deprecated tap in CLI v0.23.0 but the latest docs on the website are for v0.20.0.

@tektoncd/cli-maintainers fyi
