### ISSUE TITLE
Update docs synced to tekton-dev.netlify.dev

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/website#37]
# Expected Behavior

The docs at tekton-dev.netlify.dev for the tektoncd projects should be at the latest released versions:

* Pipelines: 0.11-rc3
* Triggers: 0.3.1 (0.4 end of march)
* CLI 0.8
* Dashboard 0.5.3 (0.6 will support beta, probably end of March?)

# Actual Behavior

The docs are currently synced from:
* https://github.com/michaelawyu/pipeline
* https://github.com/michaelawyu/triggers

# Additional Info

* The docs must [include a header that is parsed by the doc generation code](https://github.com/michaelawyu/triggers/commit/8d71084ff4e526df893002909aea340cffa87316), which is why the docs are currently synced from forks, e.g.:
   ```
   ---
   title: "Triggers"
   linkTitle: "Triggers"
   weight: 0
   description: >
     Event Triggers
   ---
   ```
* In the long run we want https://github.com/tektoncd/website/issues/34 this is just an interim update.

**Comment by skaegi** [comment]
Is it possible to provide the front matter in `<!--- --->` comments or in a separate toml file? Anyway I'll try to look at that if no-one else is...

**Comment by skaegi** [comment]
ok so commenting seems to work -- see https://github.com/skaegi/pipeline/blob/website_front_matter/docs/tasks.md#clustertask
and the commit -- https://github.com/skaegi/pipeline/commit/4a232c16a09349a7046e92d4dc8e349104fe6bb5

**Comment by skaegi** [comment]
hrm... I see that the way links are created and then used to create the sidebar and in a few other places is going to cause problems.
