### ISSUE TITLE
Include introductory videos in "Getting Started" landing page

### ISSUE THREAD

**Issue by geriom** [tektoncd/website#373]
### Feature request

Jerop Kipruto has a series of introductory videos that can be very useful for new Tekton Users:

- [Tekton for Kubernetes Cloud-Native CI/CD explained](https://www.youtube.com/watch?v=6oE7jgRuF2o)
- [Tekton CI/CD pipelines and tasks overview](https://www.youtube.com/watch?v=pW606eBa7og)
- [Tekton Chains: Extensibility, automation, and security](https://www.youtube.com/watch?v=p9K3_xtozzA)

### Use case

Some people prefer multimedia content instead of a wall of text to learn new stuff. We already have these good videos covering the basics, giving them more visibility might help many users.

**Comment by AlanGreene** [comment]
Great idea, this is something we discussed long ago for the now-defunct 'Try' page. I wasn't aware of these videos, checking them out now 👀 

fyi @jerop
