### ISSUE TITLE
https://tekton.dev/try not found

### ISSUE THREAD

**Issue by jasperjonker** [tektoncd/website#381]
# Expected Behavior
Working website for [https://tekton.dev/try](https://tekton.dev/try)

# Actual Behavior
![Screenshot_2022-05-16-103416](https://user-images.githubusercontent.com/44026484/168552314-6456c0de-6696-4ced-a4b4-6051c74e1cd4.png)

# Steps to Reproduce the Problem

1. Open [https://tekton.dev/try](https://tekton.dev/try)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by AlanGreene** [comment]
@jasperjonker this is expected as the tekton.dev/try page was removed recently. Can you share where you found that URL? Did you follow a link from somewhere else or was it something you had bookmarked perhaps?

**Comment by jasperjonker** [comment]
@AlanGreene Ahh I see. Yes I found it in the documentation here: https://tekton.dev/docs/

**Comment by AlanGreene** [comment]
Thanks for bringing this to our attention! 😸  I've opened a PR to remove the link.
