### ISSUE TITLE
Update OWNERS list

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/website#40]
# Expected Behavior

https://github.com/tektoncd/website/blob/master/OWNERS should be a list of folks we expect to review PRs in this repo.

# Actual Behavior

I think @vdemeester and I are the only ones on that list for whom that qualifies at the moment.

**Comment by skaegi** [comment]
would be great to add @sbwsg and @AlanGreene here!

**Comment by bobcatfish** [comment]
I'm gonna reopen b/c I think we should also remove folks who aren't working on this anymore, most likely at least:

- @dlorenc
- @kimsterv
- @abayer
- @lucperkins

I also want to double check: do we know that @AlanGreene and @sbwsg wanted to be OWNERS?

**Comment by AlanGreene** [comment]
I'm happy to help out 👍

**Comment by sbwsg** [comment]
Same, happy to help.
