### ISSUE TITLE
Update Note on Docs page

### ISSUE THREAD

**Issue by anneqm** [tektoncd/website#44]
# Expected Behavior
update Note for accuracy and correct spelling error... 

# Actual Behavior
Current Text: 
"Note:
Tekton provides a nunmber of interactive tutorials at try.tekton.dev for developers to get hands-on experience with the project."
Change to something like,  
"Note: Tekton provides interative tutorials at tekton-dev.com/try/ for developers to get hands-on experience with the project" 
Since first release may only have one tutorial or so, let's remove "the number of"  and/or at least correct the typo/spelling and correct to the latest URL for the try page.  This assumes the "nelify in the URL will not be needed once the new website is launched.  Hotlink works, but text should match whatever the final URL will be?  ie. is it try.tekton.dev or tekton.dev/try or tekton.dev.com/try?

# Steps to Reproduce the Problem

1.   Go here: https://tekton-dev.netlify.com/docs/
2.  see the Note statement that shoulc perhaps be updated.

# Additional Info

**Comment by AlanGreene** [comment]
Typo fixed here: https://github.com/tektoncd/website/pull/72
1 down, 1 to go...

@bobcatfish are we expecting to have a `try.tekton.dev` subdomain or should we just update the link text to reflect the actual URL `tekton.dev/try`?

**Comment by AlanGreene** [comment]
merged and deployed so closing
/close
