### ISSUE TITLE
Metrics server addon for minikube is required before to deploy Tekton pipelines

### ISSUE THREAD

**Issue by jjuarez** [tektoncd/website#443]
# Expected Behavior
To have a functional cluster at the end of the install section.

# Actual Behavior
After the "standard" installation of minikube and trying to install the Tekton stuff using the YAML manifests the pods were not working because of the lack of a proper metrics server deployment.

# Steps to Reproduce the Problem
1. Start minikube
2. Install Tekton pilines
3. The deployment is not working 

# Additional Info
This has a really easy workaround just taking in account the need of having a metrics server deployed, and the best way to do this is to enable this addon in minikube by doing:
```bash
minikube addons enable metrics-server
```
after a few seconds, we should check for the right deployment of this server:

```
kubectl top pods -A
```

and then proceed with the Tekton pipelines installation following the rest of the Getting Started section of the tutorial.

**Comment by afrittoli** [comment]
Hi @jjuarez - thanks for reporting this. 
I didn't realise we had an hard requirement on a metrics server, if you have the log from the controller would you mind pasting it here? Thank you!

**Comment by jjuarez** [comment]
Ok, thanks that's the key, I'm using kuberntes `1.25.0`

**Comment by AlanGreene** [comment]
Ah ok, in that case you should see errors when applying the pipelines yaml.

@afrittoli @geriom we should probably update the tutorials and anywhere else using minkube to pin the Kubernetes version until we land support for 1.25
