### ISSUE TITLE
Cookie banner doesn't close on click

### ISSUE THREAD

**Issue by Arhell** [tektoncd/website#447]
# Expected Behavior
close on click

# Actual Behavior
![Screenshot_2](https://user-images.githubusercontent.com/26163841/191863103-7d620656-fef9-4cbe-80cc-b09029dfcde7.png)
![Screenshot_3](https://user-images.githubusercontent.com/26163841/191863108-b7a7b516-eb86-45eb-ae1b-29f10bb972d1.png)
![Screenshot_4](https://user-images.githubusercontent.com/26163841/191863114-3dfb1a20-93d1-4429-8526-5997d3da320b.png)

Check on chrome opera

**Comment by AlanGreene** [comment]
Thanks for reporting this @Arhell. It looks like it may have been introduced by https://github.com/tektoncd/website/pull/446/files#diff-96dd75a968976edd5e03170268ed9085733f75c3fb24f992ae613c89e6de42dcL22-L25, @geriom fyi, as it worked on other previews generated before this change.

**Comment by geriom** [comment]
Moving JQuery back to header #449
