### ISSUE TITLE
More prominent calllout to Join the Tekton community in the website

### ISSUE THREAD

**Issue by dibyom** [tektoncd/website#448]
### Feature request

Current we have  "Contributions welcome " with a Read more link that takes you to the GitHub org page. Few things we could do:

1. Link to https://github.com/tektoncd/community#welcome-to-the-tekton-community instead
2. A larger callout?
3. Earlier in the webpage  so you don't have to scroll down to find how to join the Tekton community?

### Use case

1. Make How to get involved with Tekton discoverable

**Comment by dibyom** [comment]
@afrittoli @geriom @alhuizenga @lbernick

**Comment by geriom** [comment]
Related to #217

**Comment by afrittoli** [comment]
Yes, this is also a requirement for the OpenSSF badge, so we should address this.
