### ISSUE TITLE
Tekton Pipelines v0.11.0 incompatible with Katacoda k8s clusters

### ISSUE THREAD

**Issue by ncskier** [tektoncd/website#45]
# Expected Behavior
I expect to be able to use the latest version of Tekton Pipelines in a Katacoda tutorial.

# Actual Behavior
Katacoda Kubernetes clusters use version `v0.14.0` (check out [this Katacoda Kubernetes playground](https://www.katacoda.com/courses/kubernetes/playground)). Unfortunately, the latest Tekton Pipelines release (v0.11.0) requires Kubernetes version `v0.15.0`.
> :rotating_light: Please also note that the minimum version of Kubernetes required to run Tekton is now 1.15.

So, installing the latest version of Tekton Pipelines on a Katacoda Kubernetes cluster now fails with the following error:
```
{"level":"fatal","logger":"tekton","caller":"sharedmain/main.go:149","msg":"Version check failed","commit":"8c64289","error":"kubernetes version \"v1.14.0\" is not compatible, need at least \"v1.15.0\" (this can be overridden with the env var \"KUBERNETES_MIN_VERSION\")","stacktrace":"github.com/tektoncd/pipeline/vendor/knative.dev/pkg/injection/sharedmain.MainWithConfig\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/injection/sharedmain/main.go:149\ngithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/injection/sharedmain.MainWithContext\n\tgithub.com/tektoncd/pipeline/vendor/knative.dev/pkg/injection/sharedmain/main.go:114\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/controller/main.go:72\nruntime.main\n\truntime/proc.go:203"}
```

# Steps to Reproduce the Problem

1. Open a Katacoda Kubernetes environment (like [this](https://www.katacoda.com/courses/kubernetes/playground) one)
2. Install the latest version of Tekton Pipelines (`kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml`)
3. Watch the Tekton Pipeline pods crash because the Kubernetes version is too low (`kubectl get pods --namespace tekton-pipelines --watch`)

# Additional Info
It looks like I can set the `KUBERNETES_MIN_VERSION` environment variable to get around the Tekton Pipelines version constraint. However, this is not ideal, and I don't know if this will break something with Tekton Pipelines.

**Comment by AlanGreene** [comment]
https://github.com/katacoda/scenario-examples/tree/master/environments

There's an example creating a custom Kubernetes 1.16 environment, but not sure if that's of any use since it requires a Subscription.

> Creating Custom Environments on Katacoda
NOTE: This is only available with a Katacoda Subscription.


Also with Katacoda being acquired by O'Reilly towards the end of last year I don't know if they're accepting new subscriptions outside of the O'Reilly learning platform.

**Comment by anneqm** [comment]
Note that the Dasbhoard tutorial is now updated to use the previous pipeline version so it is working again.

**Comment by skaegi** [comment]
@bobcatfish I'd like us to remove the beta blocking tag as for now our tutorials can use 0.10.1 as a workaround. Still leaving this open until Katacoda updates to 1.15 or we find another way.

**Comment by popcor255** [comment]
You can use Kubernetes v1.18.0 if you use a Minikube instance. https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster

**Comment by AlanGreene** [comment]
Looks like it might be possible to specify a different kubernetes image version
e.g. https://github.com/javajon/katacoda-courses/blob/master/kubernetes-fundamentals/playground-1.17/index.json#L29

**Comment by ncskier** [comment]
> Looks like it might be possible to specify a different kubernetes image version
e.g. https://github.com/javajon/katacoda-courses/blob/8f41fac129365afcd3157344e45affad16521011/kubernetes-fundamentals/playground-1.17/index.json#L29

Unfortunately, it looks like Katacoda no longer supports that, or maybe the image id has changed?
The tutorial (https://www.katacoda.com/javajon/courses/kubernetes-fundamentals/playground-1-17) has an error setting up the environment:
<img width="1351" alt="Screen Shot 2020-04-01 at 1 46 50 PM" src="https://user-images.githubusercontent.com/16961496/78169367-4776d600-741f-11ea-8da0-ad54e908d54c.png">

> You can use Kubernetes v1.18.0 if you use a Minikube instance. https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster

That would be a good workaround if we can't specify a version with the `imageid` 👍 Are there any limitations to using minikube?

**Comment by popcor255** [comment]
Things like metrics, ingress, and storage need to be enabled through minikube addons, which is really easy but cause a different dev experience then Kubernetes. There are other resource limiations cause minikube is just one master/worker node. I have tried Tekton on minikube alot and it works perfectly fine.

**Comment by popcor255** [comment]
Hey! @ncskier Is this still an issue?  If so I would love to help! :heart:

**Comment by AlanGreene** [comment]
Looks like Katacoda finally updated the supported Kubernetes version: https://www.katacoda.community/environments.html#supported-environments

Environment | Implementation Notes | ImageID
-- | -- | --
Kubernetes Cluster 1.18 | 2 nodes with kubeadm installed, nothing running. Based on Ubuntu.Designed for teaching how to use Kubernetes from scratch | kubernetes-cluster:1.18
Kubernetes Cluster 1.18 (Pre-configured) | 2 node cluster with 1 master, 1 node. Based on Ubuntu.Run launch.sh when the scenario starts to ensure cluster is running. | kubernetes-cluster-running:1.18

The 1.14 images are now deprecated.

**Comment by AlanGreene** [comment]
Change ready locally, just need to rebase it after https://github.com/tektoncd/website/pull/161 is merged.

Updated all scenarios to use Kubernetes 1.18 and made a few small changes to the Dashboard scenario improved for stability.
