### ISSUE TITLE
Triggers and EventListeners

### ISSUE THREAD

**Issue by dibyom** [tektoncd/website#453]
# Expected Behavior

The Trigger flow diagram shows up on the page

# Actual Behavior

The trigger flow image doesn't show up

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

The request to https://tekton.dev/docs/triggers/images/TriggerFlow.svg returns a 404

Actual image is here: https://github.com/tektoncd/triggers/blob/main/docs/images/TriggerFlow.svg

**Comment by AlanGreene** [comment]
Looks like a duplicate of https://github.com/tektoncd/website/issues/340

There was a PR open attempting to address it, might need some more work to close it out.
