### ISSUE TITLE
Pipeline Metrics

### ISSUE THREAD

**Issue by franeksaww** [tektoncd/website#467]
Hi!
I found that metrics.pipelinerun.duration-type has the same argument (histogram) for histogram and gauge/lastvalue type.

![Screenshot from 2022-10-27 12-33-38](https://user-images.githubusercontent.com/58147905/198262369-362f1060-c36d-46df-960a-1e1b85600acf.png)

**Comment by AlanGreene** [comment]
Looks like there's already a PR open to fix this: https://github.com/tektoncd/pipeline/pull/5650
