### ISSUE TITLE
More sample code in In-toto Attestation Formatter please.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [tektoncd/website#489]
https://tekton.dev/docs/chains/intoto/

I see the example of the in-toto attestation for `file-SNAPSHOT.jar`, but I can't figure out how to write a task spec that generates such an attestation.

It would be incredibly helpful if the page also displayed the task spec that generated that attestation.

**Comment by AlanGreene** [comment]
@SurferJeffAtGoogle the attestation is generated by the Tekton Chains project. You can find more information about it, including installation instructions on the parent page of the one you linked: https://tekton.dev/docs/chains/
