### ISSUE TITLE
`env` missing from Pod templates doc

### ISSUE THREAD

**Issue by dibyom** [tektoncd/website#494]
The first field in https://github.com/tektoncd/pipeline/blob/main/docs/podtemplates.md#supported-fields is `env` which seems to be missing from the website: https://tekton.dev/docs/pipelines/podtemplates/#supported-fields

The [commit ](https://github.com/tektoncd/pipeline/pull/5699/files)adding this was merged in October 2022, so I'm not sure why the website is out of date

**Comment by AlanGreene** [comment]
Looks like the above linked PR was only merged at the end of December and included in Pipeline v0.43.

The latest version of the docs on the website currently shows Pipeline v0.42, so this needs to be updated.

**Comment by dibyom** [comment]
ah my bad....I looked at the PR description date, not the merge date 🤦

**Comment by AlanGreene** [comment]
website has been updated, `env` is now included in the docs for both 0.43 and 0.44
