### ISSUE TITLE
Not found the link to create-ingress.yaml on the EventListener page

### ISSUE THREAD

**Issue by konnta0** [tektoncd/website#498]
There is no link to create-ingress.yaml on the EventListener page of the following page.

https://tekton.dev/docs/triggers/eventlisteners/#exposing-an-eventlistener-using-a-kubernetes-ingress-object
> You can also use the Tekton [create-ingress](https://tekton.dev/docs/triggers/eventlisteners/getting-started/create-ingress.yaml) task to configure an Ingress object using self-signed certificates.

The following code/docs may be the subject.
https://github.com/tektoncd/triggers/blob/main/docs/getting-started/create-ingress.yaml
https://github.com/tektoncd/triggers/blob/main/docs/getting-started/README.md#create-and-execute-the-ingress-and-webhook-tasks

**Comment by AlanGreene** [comment]
Thanks for raising this @konnta0, https://github.com/tektoncd/triggers/blob/main/docs/getting-started/create-ingress.yaml (or the equivalent on the git tag for whichever release you're using) is the correct link.

Looks like an issue rewriting the URL for the website:
`https://tekton.dev/docs/triggers/eventlisteners/getting-started/create-ingress.yaml`
should be
`https://tekton.dev/docs/triggers/getting-started/create-ingress.yaml`

**Comment by konnta0** [comment]
@AlanGreene 
Thanks for the reply!

I checked again and the problem has been resolved.
Thanks for fixing it!!!
