### ISSUE TITLE
Too many repos are named with 'website'

### ISSUE THREAD

**Issue by LinuxSuRen** [tektoncd/website#5]
Please consider using a different repo name. Like tektoncd-website or others.

**Comment by matzew** [comment]
Isn't it the tektoncd/website, given the scope of this repo, inside the org ?

```
- $GOPATH/..../github.com/
    - tektoncd/
           - website
           - pipeline
...
```

no ?

**Comment by LinuxSuRen** [comment]
I get an error When I try to fork this repo. It tells me that `LinuxSuRen/website` already exists. But exists one is another one.

We might consider changing this repo to `tektoncd/tektoncd-website`.

**Comment by matzew** [comment]
think $GOPATH here

**Comment by vdemeester** [comment]
@LinuxSuRen Thanks for the issue. I feel the trick to it would be for you to rename you current fork repository to use something like `$org-website` — thus once you forked, you would rename this repository to `tektoncd-website`. I wish the GitHub UI would allow you to do that at fork though, it would solve the problem

**Comment by LinuxSuRen** [comment]
Thanks for your offer. Just feel a little trick. I've done that. And yes, it'd better if the GitHub UI could provide that way.
