### ISSUE TITLE
Link to Installing Tekton Dashboard doesn't work

### ISSUE THREAD

**Issue by anandrkskd** [tektoncd/website#500]
Link on [dashboard](https://tekton.dev/docs/dashboard) page to [Installing Tekton Dashboard](https://tekton.dev/docs/dashboard/install.md) doesn't work.

**Comment by AlanGreene** [comment]
Thanks for reporting @anandrkskd, I see many of the other links are broken too. It looks similar to https://github.com/tektoncd/website/issues/499.

In the meantime you can access the Dashboard docs in the git repo at https://github.com/tektoncd/dashboard/tree/main/docs

@afrittoli @geriom seems we have a fairly widespread problem on the website with broken links recently. As far as I can see it's links to other pages on the website from the doc content, the `.md` extension isn't being removed from the URLs. Generated content, e.g. nav, index at the bottom of root pages etc. are working correctly.

**Comment by AlanGreene** [comment]
Looks like it's caused by https://github.com/tektoncd/website/blob/73e64226b50b0a8d7c2adc70e71e039b6c3a8b71/sync/sync.py#L244

It's replacing the map instead of combining them so it's only processing images.
