### ISSUE TITLE
update docsy as a submodule

### ISSUE THREAD

**Issue by Arhell** [tektoncd/website#521]
@geriom ?

**Comment by geriom** [comment]
We are indeed [one version behind](https://github.com/google/docsy/releases).  If you want to give it a try and update to the latest release, run the corresponding [hugo command](https://gohugo.io/hugo-modules/use-modules/#update-all-modules):

```bash
hugo mod get -u
```

That should automatically update both `go.mod` and  `go.sum`. Test that nothing is broken and open a PR.
