### ISSUE TITLE
Install Tekton Pipelines

### ISSUE THREAD

**Issue by makshop99** [tektoncd/website#527]
The link in the section "Additional configuration options" does not work, the page linked can't be found. 
No problem, just wanted to inform you, guys. 
In general great documentation.

**Comment by geriom** [comment]
Thanks for the report. The docs use the latest version of the Pipelines repo, the fix will be applied in the next release. In the meantime you can find the target doc at https://tekton.dev/vault/pipelines-main/additional-configs/

**Comment by geriom** [comment]
The latest version of the docs has the correct link
