### ISSUE TITLE
Dashboard - improve "which release should I use" reference

### ISSUE THREAD

**Issue by anneqm** [tektoncd/website#54]
# Expected Behavior
In "Important" section, please point to details for which release to use at this link https://github.com/tektoncd/dashboard#which-version-should-i-use

# Actual Behavior
Currently points to releases page,https://github.com/tektoncd/dashboard/releases. The readme.md page would be a better choice to point directly to this section https://github.com/tektoncd/dashboard#which-version-should-i-use  to quickly determine which version combination to use. 

# Steps to Reproduce the Problem

1. go to https://tekton-dev.netlify.com/docs/dashboard/
2. scroll down to important highlighted section. 
3. See URL pointing to https://github.com/tektoncd/dashboard/releases

# Additional Info

**Comment by AlanGreene** [comment]
/close

Thanks @popcor255
