### ISSUE TITLE
Results - Broken Mermaid Charts

### ISSUE THREAD

**Issue by michaelsatish** [tektoncd/website#541]
Hello,

I was reading the Results documentation and noticed the below links has broken mermaid charts.

1. https://tekton.dev/docs/results/#life-of-a-result
2. https://tekton.dev/docs/results/#life-of-a-result

**Comment by avinal** [comment]
Thank you @michaelsatish, I was about to report this. @geriom from our [discussion in slack](https://tektoncd.slack.com/archives/CJ4ERJWAU/p1676557813961939) it should work just fine. I also went through the docsy docs. The only requirement was Hugo version >=0.93, The website uses 0.107, so it fine there.

https://github.com/tektoncd/website/blob/471b58831215259f60faf6adefecbcaf9f622482/netlify.toml#L6

**Comment by geriom** [comment]
Thank you @michaelsatish 

It seems that a recent change in Docsy broke mermaid. I'm adding back mermaid support in [this PR](https://github.com/tektoncd/website/pull/530/files#diff-ed3b5a25a9efb89d0cebc442bd8b68c2b2caa45746f6633f89aa4a0e45410f9a), which includes a mermaid diagram that represents Tekton Chains. If you check the preview you can see the results diagrams rendering correctly.

Docsy is currently undergoing a massive upgrade to support bootstrap 5. Once the new Docsy release is out I'll update the site and revisit this change if necessary.
