### ISSUE TITLE
Yaml not rendered correctly.

### ISSUE THREAD

**Issue by geriom** [tektoncd/website#549]
The tabs in https://tekton.dev/docs/pipelines/tasks/ are not rendering the content correctly. It's probably as simple as changing the delimiter from `{{%` to `{{<` or the other way around.

**Comment by AlanGreene** [comment]
This was partially fixed on main, see https://github.com/tektoncd/pipeline/issues/6636
There are a few similar issues remaining, e.g. https://github.com/tektoncd/pipeline/issues/6697

**Comment by chitrangpatel** [comment]
https://github.com/tektoncd/pipeline/pull/6750 tries to fix this.

**Comment by chitrangpatel** [comment]
The PR that fixes it was merged. Although I'm not sure when the website will be updated. I wonder if its after the Tekton Pipelines next release since the fix was in that repo?
