### ISSUE TITLE
New endpoint: https://tekton.dev/slsa-predicate

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/website#561]
Tekton Chains creates SLSA provenance. One of the critical provenance fields is the buildType which is meant to be a url to the build description. Currently, any docs from the Chains repo can be hosted under https://tekton.dev/docs/chains/. Since the SLSA predicate is a specialized use case, we would like to host it under https://tekton.dev/slsa-predicate/chains/ if possible. 

cc @tektoncd/chains-maintainers

**Comment by afrittoli** [comment]
Hello @chitrangpatel - it should be possible to setup something. We can also setup subdomains if that helps.

**Comment by chitrangpatel** [comment]
Thanks @afrittoli that would help. I believe @wlynch also created this PR https://github.com/tektoncd/website/pull/562 to address this.
