### ISSUE TITLE
Dashboard docs - add link or pointer to tutorial for reference

### ISSUE THREAD

**Issue by anneqm** [tektoncd/website#57]
# Expected Behavior
Let the user know there is a tutorial about the dashboard on the Try page

# Actual Behavior
The dashboard documentation page does not mention the tutorial. I think it would be useful to mention that the tutorial is available from the try page, and perhaps add direct link? 

# Steps to Reproduce the Problem

1. https://tekton.netlify.com/docs/dashboard
2. read thru the page
3. no mention of existing tutorial to check out

# Additional Info

**Comment by popcor255** [comment]
[pr](https://github.com/tektoncd/website/pull/63)
