### ISSUE TITLE
Install Tekton Pipelines - K8s version discrepancy?

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/website#614]
This page `https://tekton.dev/docs/pipelines/install/` references:

> A Kubernetes cluster running version 1.25 or later.

However on releases (https://github.com/tektoncd/pipeline/releases) it says:

> [Tekton Pipeline release v0.61.0 "Ragdoll Data"](https://github.com/tektoncd/pipeline/releases/tag/v0.61.0)
> [T]he minimum Kubernetes version supported by Tekton is now 1.28.

Does the installation documentation need amending?

**Comment by AlanGreene** [comment]
Hi @mtcolman, thanks for raising this.

Yes the documentation should be updated. Would you be interested in submitting a PR? If you click the 'Edit this page' button on the right of the install doc it will bring you to the correct place.

**Comment by AlanGreene** [comment]
Opened a PR: https://github.com/tektoncd/pipeline/pull/8122

**Comment by AlanGreene** [comment]
Updated docs published to the website
