### ISSUE TITLE
ascii demo need to be done with v1beta1

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/website#66]
The demo on the front page (using `asciimedia` ?) needs to be redone with `v1beta1` APIs. Right now it is showing `v1alpha1` :stuck_out_tongue_closed_eyes: 

![2020-04-01-124031_1060x373_scrot](https://user-images.githubusercontent.com/6508/78128392-22ca3080-7416-11ea-8ec6-c35680c08fcd.png)

/kind documentation

**Comment by AlanGreene** [comment]
This one's done, thanks @joellord 

/close
