### ISSUE TITLE
Configure Google Analytics for the website

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/website#73]
# Expected Behavior

The website should report information about views and visitors through an analytics platform.

# Actual Behavior

We appear to have Google Analytics already configured for the website but it's unclear whose account the ID is tied to, and therefore where to go to see the current stats.  We also probably need to figure out some way for these analytics to be shared with the wider group.

# Additional Info

See [config.toml ](https://github.com/tektoncd/website/blob/master/config.toml#L51-L53) for the current configuration.

**Comment by popcor255** [comment]
Netlify has their own set of analytic tools out of the box. Can we use that?
