### ISSUE TITLE
Both of the getting started links on the triggers page are dead

### ISSUE THREAD

**Issue by gswallow** [tektoncd/website#81]
# Expected Behavior

Click on a getting started link (e.g. create a github webhook), see documentation.

# Actual Behavior

Click on a getting started link, get a 404.

# Steps to Reproduce the Problem

1. Start browser
2. Visit documentation
3. Haz sad.

# Additional Info

https://tekton.dev/docs/triggers/

**Comment by AlanGreene** [comment]
Relevant content:
- [Create an Ingress on the EventListener Service](https://github.com/tektoncd/triggers/blob/master/docs/create-ingress.yaml)
- [Create a GitHub webhook](https://github.com/tektoncd/triggers/blob/master/docs/create-webhook.yaml)

They're not referenced in the website docs [sync config](https://github.com/tektoncd/website/blob/master/sync/config/triggers.yaml).
