### ISSUE TITLE
Relative Links are Broken.

### ISSUE THREAD

**Issue by popcor255** [tektoncd/website#89]
# Expected Behavior
I accept that when I click on [Tekton Pipeline Link](https://github.com/tektoncd/dashboard/releases) it should give me some type of documentation.

# Actual Behavior
It sends me to the github documentation

# Steps to Reproduce the Problem

1. Go to https://tekton.dev/docs/pipelines/
2. Click on pipeline metric
3. It should send you to https://tekton.dev/docs/pipelines/metrics

# Additional Info

I think the scraper should change the absolute link to the relative link if the relative link does not return a 400 type error.

**Comment by AlanGreene** [comment]
Only the files listed here are synced from the pipeline docs: https://github.com/tektoncd/website/blob/e13567cedbb15b9b155f7ddd22c2fa53e18c871c/sync/config/pipelines.yaml#L27-L41

https://github.com/tektoncd/pipeline/blob/master/docs/metrics.md and a number of other files aren't included in that list.

**Comment by popcor255** [comment]
Yeah, I understand. In order to fix the broken url add the doc in the yaml. I think it is somewhat unreasonable to expect us to keep up with every doc in every repo.

It makes more sense for the script to transform all the links. You should only transform the links that wont result in a 400 response.

Current sync
```python
def transform_links(link_prefix, dest_prefix, files):
    for f in files:
        for k in f:
            dest_path = f'{dest_prefix}/{f[k]}'
            for line in fileinput.input(dest_path, inplace=1):
                line = re.sub(RELATIVE_LINKS_RE, r'[\1](' + link_prefix + r'\2\3)', line.rstrip())
                print(line)
```

Proposing Change
```
def transform_links(link_prefix, dest_prefix, files):
    for f in files:
        for k in f:
            dest_path = f'{dest_prefix}/{f[k]}'
            for line in fileinput.input(dest_path, inplace=1):
                relative_link = re.sub(RELATIVE_LINKS_RE, r'[\1](' + link_prefix + r'\2\3)', line.rstrip())
                if validUrl(relative_link):
                    link = relative_link
                print(line)
```

I could be wrong and maybe always making sure it is update is a better solution, but this is what I had in mind.

**Comment by popcor255** [comment]
Ok, so I have no idea what transofrm links does. I thought it transformed the link inside the content. Not really sure what this function even does anymore. Im just add the doc to the yaml like @AlanGreene said.

**Comment by popcor255** [comment]
This is a duplicate of https://github.com/tektoncd/website/issues/65
