### ISSUE TITLE
Doc bug: 

### ISSUE THREAD

**Issue by JCzz** [tektoncd/website#94]
Links from: https://tekton.dev/docs/triggers/

In the bottom: Getting Started Tasks, links 404

https://tekton.dev/docs/triggers/create-webhook.yaml
https://tekton.dev/docs/triggers/create-ingress.yaml

**Comment by AlanGreene** [comment]
Thanks for reporting, it looks like this is a duplicate of https://github.com/tektoncd/website/issues/81

In the meantime you can find the referenced samples here:
- [Create an Ingress on the EventListener Service](https://github.com/tektoncd/triggers/blob/master/docs/create-ingress.yaml)
- [Create a GitHub webhook](https://github.com/tektoncd/triggers/blob/master/docs/create-webhook.yaml)
