### ISSUE TITLE
Title blue on black is not readable.

### ISSUE THREAD

**Issue by steren** [tektoncd/website#98]
![image](https://user-images.githubusercontent.com/360895/80514243-16fa5d00-8935-11ea-9520-c9cc370c38b9.png)

**Comment by popcor255** [comment]
Hello @steren! :smiley_cat:
That is a good point. Do you have suggestions? Do you think it would be better to change it to the black and white version instead? Here is some art you can choose from [link](https://github.com/cdfoundation/artwork/tree/master/tekton). Maybe you can pick something that you think would look cool! :sunglasses:
